---@class HardcoreBlacklist
local HardcoreBlacklist = QuestieLoader:CreateModule("HardcoreBlacklist")


---@return table<QuestId, boolean>
function HardcoreBlacklist:Load()
    return {
        [5892] = true, -- Irondeep Supplies
        [5893] = true, -- Coldtooth Supplies
        [6741] = true, -- More Booty!
        [6781] = true, -- More Armor Scraps
        [6801] = true, -- Lokholar the Ice Lord
        [6825] = true, -- Call of Air - Guse's Fleet
        [6826] = true, -- Call of Air - Jeztor's Fleet
        [6827] = true, -- Call of Air - Mulverick's Fleet
        [6846] = true, -- Begin the Attack!
        [6847] = true, -- Master Ryson's All Seeing Eye
        [6848] = true, -- Master Ryson's All Seeing Eye
        [6861] = true, -- Zinfizzlex's Portable Shredder Unit
        [6862] = true, -- Zinfizzlex's Portable Shredder Unit
        [6881] = true, -- Ivus the Forest Lord
        [6901] = true, -- Launch the Attack!
        [6941] = true, -- Call of Air - Vipore's Fleet
        [6942] = true, -- Call of Air - Slidore's Fleet
        [6943] = true, -- Call of Air - Ichman's Fleet
        [6982] = true, -- Coldtooth Supplies
        [6985] = true, -- Irondeep Supplies
        [7001] = true, -- Empty Stables
        [7002] = true, -- Ram Hide Harnesses
        [7026] = true, -- Ram Riding Harnesses
        [7027] = true, -- Empty Stables
        [7081] = true, -- Alterac Valley Graveyards
        [7082] = true, -- The Graveyards of Alterac
        [7101] = true, -- Towers and Bunkers
        [7102] = true, -- Towers and Bunkers
        [7121] = true, -- The Quartermaster
        [7122] = true, -- Capture a Mine
        [7123] = true, -- Speak with our Quartermaster
        [7124] = true, -- Capture a Mine
        [7141] = true, -- The Battle of Alterac
        [7142] = true, -- The Battle for Alterac
        [7161] = true, -- Proving Grounds
        [7162] = true, -- Proving Grounds
        [7163] = true, -- Rise and Be Recognized
        [7164] = true, -- Honored Amongst the Clan
        [7165] = true, -- Earned Reverence
        [7166] = true, -- Legendary Heroes
        [7167] = true, -- The Eye of Command
        [7168] = true, -- Rise and Be Recognized
        [7169] = true, -- Honored Amongst the Guard
        [7170] = true, -- Earned Reverence
        [7171] = true, -- Legendary Heroes
        [7172] = true, -- The Eye of Command
        [7181] = true, -- The Legend of Korrak
        [7202] = true, -- Korrak the Bloodrager
        [7221] = true, -- Speak with Prospector Stonehewer
        [7222] = true, -- Speak with Voggah Deathgrip
        [7223] = true, -- Armor Scraps
        [7224] = true, -- Enemy Booty
        [7241] = true, -- In Defense of Frostwolf
        [7261] = true, -- The Sovereign Imperative
        [7281] = true, -- Brotherly Love
        [7282] = true, -- Brotherly Love
        [7301] = true, -- Fallen Sky Lords
        [7302] = true, -- Fallen Sky Lords
        [7361] = true, -- Favor Amongst the Darkspear
        [7362] = true, -- Ally of the Tauren
        [7363] = true, -- The Human Condition
        [7364] = true, -- Gnomeregan Bounty
        [7365] = true, -- Staghelm's Requiem
        [7366] = true, -- The Archbishop's Mercy
        [7367] = true, -- Defusing the Threat
        [7368] = true, -- Defusing the Threat
        [7381] = true, -- The Return of Korrak
        [7382] = true, -- Korrak the Everliving
        [7385] = true, -- A Gallon of Blood
        [7386] = true, -- Crystal Cluster
        [7401] = true, -- WANTED: Dwarves!
        [7402] = true, -- WANTED: Orcs!
        [7421] = true, -- Darkspear Defense
        [7422] = true, -- Tuft it Out
        [7423] = true, -- I've Got A Fever For More Bone Chips
        [7424] = true, -- What the Hoof?
        [7425] = true, -- Staghelm's Mojo Jamboree
        [7426] = true, -- One Man's Love
        [7427] = true, -- Wanted: MORE DWARVES!
        [7428] = true, -- Wanted: MORE ORCS!
        [7788] = true, -- Vanquish the Invaders!
        [7789] = true, -- Quell the Silverwing Usurpers
        [7871] = true, -- Vanquish the Invaders!
        [7872] = true, -- Vanquish the Invaders!
        [7873] = true, -- Vanquish the Invaders!
        [7874] = true, -- Quell the Silverwing Usurpers
        [7875] = true, -- Quell the Silverwing Usurpers
        [7876] = true, -- Quell the Silverwing Usurpers
        [7886] = true, -- Talismans of Merit
        [7887] = true, -- Talismans of Merit
        [7888] = true, -- Talismans of Merit
        [7921] = true, -- Talismans of Merit
        [7922] = true, -- Mark of Honor
        [7923] = true, -- Mark of Honor
        [7924] = true, -- Mark of Honor
        [7925] = true, -- Mark of Honor
        [8001] = true, -- Warsong Outriders <NYI> <TXT>
        [8002] = true, -- Silverwing Sentinels <NYI> <TXT>
        [8080] = true, -- Arathi Basin Resources!
        [8081] = true, -- More Resource Crates
        [8105] = true, -- The Battle for Arathi Basin!
        [8114] = true, -- Control Four Bases
        [8115] = true, -- Control Five Bases
        [8120] = true, -- The Battle for Arathi Basin!
        [8121] = true, -- Take Four Bases
        [8122] = true, -- Take Five Bases
        [8123] = true, -- Cut Arathor Supply Lines
        [8124] = true, -- More Resource Crates
        [8154] = true, -- Arathi Basin Resources!
        [8155] = true, -- Arathi Basin Resources!
        [8156] = true, -- Arathi Basin Resources!
        [8157] = true, -- More Resource Crates
        [8158] = true, -- More Resource Crates
        [8159] = true, -- More Resource Crates
        [8160] = true, -- Cut Arathor Supply Lines
        [8161] = true, -- Cut Arathor Supply Lines
        [8162] = true, -- Cut Arathor Supply Lines
        [8163] = true, -- More Resource Crates
        [8164] = true, -- More Resource Crates
        [8165] = true, -- More Resource Crates
        [8166] = true, -- The Battle for Arathi Basin!
        [8167] = true, -- The Battle for Arathi Basin!
        [8168] = true, -- The Battle for Arathi Basin!
        [8169] = true, -- The Battle for Arathi Basin!
        [8170] = true, -- The Battle for Arathi Basin!
        [8171] = true, -- The Battle for Arathi Basin!
        [8260] = true, -- Arathor Basic Care Package
        [8261] = true, -- Arathor Standard Care Package
        [8262] = true, -- Arathor Advanced Care Package
        [8263] = true, -- Defiler's Basic Care Package
        [8264] = true, -- Defiler's Standard Care Package
        [8265] = true, -- Defiler's Advanced Care Package
        [8266] = true, -- Ribbons of Sacrifice
        [8267] = true, -- Ribbons of Sacrifice
        [8268] = true, -- Ribbons of Sacrifice
        [8269] = true, -- Ribbons of Sacrifice
        [8271] = true, -- Hero of the Stormpike
        [8272] = true, -- Hero of the Frostwolf
        [8289] = true, -- Talismans of Merit
        [8290] = true, -- Vanquish the Invaders
        [8291] = true, -- Vanquish the Invaders!
        [8292] = true, -- Talismans of Merit
        [8293] = true, -- Mark of Honor
        [8294] = true, -- Quell the Silverwing Usurpers
        [8295] = true, -- Quell the Silverwing Usurpers
        [8296] = true, -- Mark of Honor
        [8297] = true, -- Arathi Basin Resources!
        [8298] = true, -- More Resource Crates
        [8299] = true, -- Cut Arathor Supply Lines
        [8300] = true, -- More Resource Crates
        [8368] = true, -- Battle of Warsong Gulch
        [8367] = true, -- For Great Honor
        [8369] = true, -- Invaders of Alterac Valley
        [8370] = true, -- Conquering Arathi Basin
        [8371] = true, -- Concerted Efforts
        [8372] = true, -- Fight for Warsong Gulch
        [8374] = true, -- Claiming Arathi Basin
        [8375] = true, -- Remember Alterac Valley
        [8383] = true, -- Remember Alterac Valley
        [8384] = true, -- Claiming Arathi Basin
        [8385] = true, -- Concerted Efforts
        [8386] = true, -- Fight for Warsong Gulch
        [8387] = true, -- Invaders of Alterac Valley
        [8388] = true, -- For Great Honor
        [8389] = true, -- Battle of Warsong Gulch
        [8390] = true, -- Conquering Arathi Basin
        [8391] = true, -- Claiming Arathi Basin
        [8392] = true, -- Claiming Arathi Basin
        [8393] = true, -- Claiming Arathi Basin
        [8394] = true, -- Claiming Arathi Basin
        [8395] = true, -- Claiming Arathi Basin
        [8396] = true, -- Claiming Arathi Basin
        [8397] = true, -- Claiming Arathi Basin
        [8398] = true, -- Claiming Arathi Basin
        [8399] = true, -- Fight for Warsong Gulch
        [8400] = true, -- Fight for Warsong Gulch
        [8401] = true, -- Fight for Warsong Gulch
        [8402] = true, -- Fight for Warsong Gulch
        [8403] = true, -- Fight for Warsong Gulch
        [8404] = true, -- Fight for Warsong Gulch
        [8405] = true, -- Fight for Warsong Gulch
        [8406] = true, -- Fight for Warsong Gulch
        [8407] = true, -- Fight for Warsong Gulch
        [8408] = true, -- Fight for Warsong Gulch
        [8426] = true, -- Battle of Warsong Gulch
        [8427] = true, -- Battle of Warsong Gulch
        [8428] = true, -- Battle of Warsong Gulch
        [8429] = true, -- Battle of Warsong Gulch
        [8430] = true, -- Battle of Warsong Gulch
        [8431] = true, -- Battle of Warsong Gulch
        [8432] = true, -- Battle of Warsong Gulch
        [8433] = true, -- Battle of Warsong Gulch
        [8434] = true, -- Battle of Warsong Gulch
        [8435] = true, -- Battle of Warsong Gulch
        [8436] = true, -- Conquering Arathi Basin
        [8437] = true, -- Conquering Arathi Basin
        [8438] = true, -- Conquering Arathi Basin
        [8439] = true, -- Conquering Arathi Basin
        [8440] = true, -- Conquering Arathi Basin
        [8441] = true, -- Conquering Arathi Basin
        [8442] = true, -- Conquering Arathi Basin
        [8443] = true, -- Conquering Arathi Basin
    }
end
