---@class TitanReforgedQuestFixes
local TitanReforgedQuestFixes = QuestieLoader:CreateModule("TitanReforgedQuestFixes")
---@type QuestieDB
local QuestieDB = QuestieLoader:ImportModule("QuestieDB")
---@type ZoneDB
local ZoneDB = QuestieLoader:ImportModule("ZoneDB")
---@type QuestieProfessions
local QuestieProfessions = QuestieLoader:ImportModule("QuestieProfessions")

---Returns Titan-only quest templates applied before database compilation.
---@return table<QuestId, table>
function TitanReforgedQuestFixes.LoadQuests()
    local questKeys = QuestieDB.questKeys
    local raceIDs = QuestieDB.raceKeys
    local classIDs = QuestieDB.classKeys
    local factionIDs = QuestieDB.factionIDs
    local zoneIDs = ZoneDB.zoneIDs
    local sortKeys = QuestieDB.sortKeys
    local profKeys = QuestieProfessions.professionKeys
    local specialFlags = QuestieDB.specialFlags
    local questFlags = QuestieDB.questFlags

    return {
        [93950] = { -- A Message From The Stars
            [questKeys.name] = "A Message From The Stars",
            [questKeys.startedBy] = {{257012}},
            [questKeys.finishedBy] = {{257012}},
            [questKeys.requiredLevel] = 1,
            [questKeys.questLevel] = 80,
            [questKeys.requiredRaces] = raceIDs.NONE,
            [questKeys.objectivesText] = {"Accept Algalon's Gift."},
            [questKeys.zoneOrSort] = sortKeys.TITAN_REFORGED_REALM,
            [questKeys.specialFlags] = specialFlags.NONE,
            [questKeys.questFlags] = questFlags.NONE,
        },
        [93975] = { -- Ragnaros Must Die!
            [questKeys.name] = "Ragnaros Must Die!",
            [questKeys.startedBy] = {{20735}},
            [questKeys.finishedBy] = {{20735}},
            [questKeys.requiredLevel] = 80,
            [questKeys.questLevel] = 80,
            [questKeys.requiredRaces] = raceIDs.NONE,
            [questKeys.objectivesText] = {"Kill Ragnaros."},
            [questKeys.objectives] = {{{11502}}},
            [questKeys.zoneOrSort] = zoneIDs.MOLTEN_CORE,
            [questKeys.specialFlags] = specialFlags.REPEATABLE,
            [questKeys.questFlags] = questFlags.WEEKLY,
            [questKeys.exclusiveTo] = {94577,94579,95037,96312,96315,96318},
            [questKeys.reputationReward] = {{factionIDs.KIRIN_TOR,75}},
        },
        [94376] = { -- Titanic Power
            [questKeys.name] = "Titanic Power",
            [questKeys.startedBy] = {{257403}},
            [questKeys.finishedBy] = {{257403}},
            [questKeys.requiredLevel] = 69,
            [questKeys.questLevel] = 80,
            [questKeys.requiredRaces] = raceIDs.NONE,
            [questKeys.objectivesText] = {"Speak to Algalon and learn about Titanic Embers."},
            [questKeys.zoneOrSort] = zoneIDs.STORM_PEAKS,
            [questKeys.specialFlags] = specialFlags.NONE,
            [questKeys.questFlags] = questFlags.NONE,
        },
        [94576] = { -- Find a New Way
            [questKeys.name] = "Find a New Way",
            [questKeys.startedBy] = {{31136}},
            [questKeys.finishedBy] = {{31136}},
            [questKeys.requiredLevel] = 80,
            [questKeys.questLevel] = 80,
            [questKeys.requiredRaces] = raceIDs.NONE,
            [questKeys.objectivesText] = {"Find a way to power the Wind - Kissed Blade, then return to High Warlord Uro in the sewers of Dalaran."},
            [questKeys.zoneOrSort] = sortKeys.LEGENDARY,
            [questKeys.specialFlags] = specialFlags.NONE,
            [questKeys.questFlags] = questFlags.NONE,
            [questKeys.preQuestSingle] = {7787},
        },
        [94577] = { -- Kael'thas Must Die!
            [questKeys.name] = "Kael'thas Must Die!",
            [questKeys.startedBy] = {{20735}},
            [questKeys.finishedBy] = {{20735}},
            [questKeys.requiredLevel] = 80,
            [questKeys.questLevel] = 80,
            [questKeys.requiredRaces] = raceIDs.NONE,
            [questKeys.objectivesText] = {"Kill Kael'thas Sunstrider in Tempest Keep."},
            [questKeys.objectives] = {{{19622}}},
            [questKeys.zoneOrSort] = zoneIDs.TEMPEST_KEEP,
            [questKeys.specialFlags] = specialFlags.REPEATABLE,
            [questKeys.questFlags] = questFlags.WEEKLY,
            [questKeys.exclusiveTo] = {93975,94579,95037,96312,96315,96318},
            [questKeys.reputationReward] = {{factionIDs.KIRIN_TOR,75}},
        },
        [94579] = { -- Patchwerk Must Die!
            [questKeys.name] = "Patchwerk Must Die!",
            [questKeys.startedBy] = {{20735}},
            [questKeys.finishedBy] = {{20735}},
            [questKeys.requiredLevel] = 80,
            [questKeys.questLevel] = 80,
            [questKeys.requiredRaces] = raceIDs.NONE,
            [questKeys.objectivesText] = {"Kill Patchwerk."},
            [questKeys.objectives] = {{{16028}}},
            [questKeys.zoneOrSort] = zoneIDs.NAXXRAMAS,
            [questKeys.specialFlags] = specialFlags.REPEATABLE,
            [questKeys.questFlags] = questFlags.WEEKLY,
            [questKeys.exclusiveTo] = {93975,94577,95037,96312,96315,96318},
            [questKeys.reputationReward] = {{factionIDs.KIRIN_TOR,75}},
        },
        [95037] = { -- Lord Jaraxxus Must Die!
            [questKeys.name] = "Lord Jaraxxus Must Die!",
            [questKeys.startedBy] = {{20735}},
            [questKeys.finishedBy] = {{20735}},
            [questKeys.requiredLevel] = 80,
            [questKeys.questLevel] = 80,
            [questKeys.requiredRaces] = raceIDs.NONE,
            [questKeys.objectivesText] = {"Kill Lord Jaraxxus."},
            [questKeys.objectives] = {{{34780}}},
            [questKeys.zoneOrSort] = zoneIDs.TRIAL_OF_THE_CRUSADER,
            [questKeys.specialFlags] = specialFlags.REPEATABLE,
            [questKeys.questFlags] = questFlags.WEEKLY,
            [questKeys.exclusiveTo] = {93975,94577,94579,96312,96315,96318},
            [questKeys.reputationReward] = {{factionIDs.KIRIN_TOR,75}},
        },
        [95072] = { -- Hoodoo Embodiment
            [questKeys.name] = "Hoodoo Embodiment",
            [questKeys.startedBy] = {{15042}},
            [questKeys.finishedBy] = {{15042}},
            [questKeys.requiredLevel] = 80,
            [questKeys.questLevel] = 80,
            [questKeys.requiredRaces] = raceIDs.NONE,
            [questKeys.requiredClasses] = classIDs.WARLOCK,
            [questKeys.objectives] = {nil,nil,{{274994},{19819}}},
            [questKeys.zoneOrSort] = zoneIDs.ZUL_GURUB,
            [questKeys.specialFlags] = specialFlags.REPEATABLE,
            [questKeys.requiredMinRep] = {factionIDs.ZANDALAR_TRIBE,3000},
            [questKeys.reputationReward] = {{factionIDs.ZANDALAR_TRIBE,250}},
        },
        [95074] = { -- Falcon's Prophecy
            [questKeys.name] = "Falcon's Prophecy",
            [questKeys.startedBy] = {{15042}},
            [questKeys.finishedBy] = {{15042}},
            [questKeys.requiredLevel] = 80,
            [questKeys.questLevel] = 80,
            [questKeys.requiredRaces] = raceIDs.NONE,
            [questKeys.requiredClasses] = classIDs.HUNTER,
            [questKeys.objectives] = {nil,nil,{{274994},{19816}}},
            [questKeys.zoneOrSort] = zoneIDs.ZUL_GURUB,
            [questKeys.specialFlags] = specialFlags.REPEATABLE,
            [questKeys.requiredMinRep] = {factionIDs.ZANDALAR_TRIBE,3000},
            [questKeys.reputationReward] = {{factionIDs.ZANDALAR_TRIBE,250}},
        },
        [95075] = { -- Destructive Prophecy
            [questKeys.name] = "Destructive Prophecy",
            [questKeys.startedBy] = {{15042}},
            [questKeys.finishedBy] = {{15042}},
            [questKeys.requiredLevel] = 80,
            [questKeys.questLevel] = 80,
            [questKeys.requiredRaces] = raceIDs.NONE,
            [questKeys.requiredClasses] = classIDs.PRIEST,
            [questKeys.objectives] = {nil,nil,{{274994},{19820}}},
            [questKeys.zoneOrSort] = zoneIDs.ZUL_GURUB,
            [questKeys.specialFlags] = specialFlags.REPEATABLE,
            [questKeys.requiredMinRep] = {factionIDs.ZANDALAR_TRIBE,3000},
            [questKeys.reputationReward] = {{factionIDs.ZANDALAR_TRIBE,250}},
        },
        [95076] = { -- Divine Prophecy
            [questKeys.name] = "Divine Prophecy",
            [questKeys.startedBy] = {{15042}},
            [questKeys.finishedBy] = {{15042}},
            [questKeys.requiredLevel] = 80,
            [questKeys.questLevel] = 80,
            [questKeys.requiredRaces] = raceIDs.NONE,
            [questKeys.requiredClasses] = classIDs.PALADIN,
            [questKeys.objectives] = {nil,nil,{{274994},{19815}}},
            [questKeys.zoneOrSort] = zoneIDs.ZUL_GURUB,
            [questKeys.specialFlags] = specialFlags.REPEATABLE,
            [questKeys.requiredMinRep] = {factionIDs.ZANDALAR_TRIBE,3000},
            [questKeys.reputationReward] = {{factionIDs.ZANDALAR_TRIBE,250}},
        },
        [95077] = { -- Redeemer's Prophecy
            [questKeys.name] = "Redeemer's Prophecy",
            [questKeys.startedBy] = {{15042}},
            [questKeys.finishedBy] = {{15042}},
            [questKeys.requiredLevel] = 80,
            [questKeys.questLevel] = 80,
            [questKeys.requiredRaces] = raceIDs.NONE,
            [questKeys.requiredClasses] = classIDs.PALADIN,
            [questKeys.objectives] = {nil,nil,{{274994},{19815}}},
            [questKeys.zoneOrSort] = zoneIDs.ZUL_GURUB,
            [questKeys.specialFlags] = specialFlags.REPEATABLE,
            [questKeys.requiredMinRep] = {factionIDs.ZANDALAR_TRIBE,3000},
            [questKeys.reputationReward] = {{factionIDs.ZANDALAR_TRIBE,250}},
        },
        [95078] = { -- Prophecy of Protection
            [questKeys.name] = "Prophecy of Protection",
            [questKeys.startedBy] = {{15042}},
            [questKeys.finishedBy] = {{15042}},
            [questKeys.requiredLevel] = 80,
            [questKeys.questLevel] = 80,
            [questKeys.requiredRaces] = raceIDs.NONE,
            [questKeys.requiredClasses] = classIDs.WARRIOR,
            [questKeys.objectives] = {nil,nil,{{274994},{19813}}},
            [questKeys.zoneOrSort] = zoneIDs.ZUL_GURUB,
            [questKeys.specialFlags] = specialFlags.REPEATABLE,
            [questKeys.requiredMinRep] = {factionIDs.ZANDALAR_TRIBE,3000},
            [questKeys.reputationReward] = {{factionIDs.ZANDALAR_TRIBE,250}},
        },
        [95079] = { -- Stormcaller's Prophecy
            [questKeys.name] = "Stormcaller's Prophecy",
            [questKeys.startedBy] = {{15042}},
            [questKeys.finishedBy] = {{15042}},
            [questKeys.requiredLevel] = 80,
            [questKeys.questLevel] = 80,
            [questKeys.requiredRaces] = raceIDs.NONE,
            [questKeys.requiredClasses] = classIDs.SHAMAN,
            [questKeys.objectives] = {nil,nil,{{274994},{19817}}},
            [questKeys.zoneOrSort] = zoneIDs.ZUL_GURUB,
            [questKeys.specialFlags] = specialFlags.REPEATABLE,
            [questKeys.requiredMinRep] = {factionIDs.ZANDALAR_TRIBE,3000},
            [questKeys.reputationReward] = {{factionIDs.ZANDALAR_TRIBE,250}},
        },
        [95080] = { -- Witchdoctor's Prophecy
            [questKeys.name] = "Witchdoctor's Prophecy",
            [questKeys.startedBy] = {{15042}},
            [questKeys.finishedBy] = {{15042}},
            [questKeys.requiredLevel] = 80,
            [questKeys.questLevel] = 80,
            [questKeys.requiredRaces] = raceIDs.NONE,
            [questKeys.requiredClasses] = classIDs.SHAMAN,
            [questKeys.objectives] = {nil,nil,{{274994},{19817}}},
            [questKeys.zoneOrSort] = zoneIDs.ZUL_GURUB,
            [questKeys.specialFlags] = specialFlags.REPEATABLE,
            [questKeys.requiredMinRep] = {factionIDs.ZANDALAR_TRIBE,3000},
            [questKeys.reputationReward] = {{factionIDs.ZANDALAR_TRIBE,250}},
        },
        [95081] = { -- Guardian's Prophecy
            [questKeys.name] = "Guardian's Prophecy",
            [questKeys.startedBy] = {{15042}},
            [questKeys.finishedBy] = {{15042}},
            [questKeys.requiredLevel] = 80,
            [questKeys.questLevel] = 80,
            [questKeys.requiredRaces] = raceIDs.NONE,
            [questKeys.requiredClasses] = classIDs.DRUID,
            [questKeys.objectives] = {nil,nil,{{274994},{19821}}},
            [questKeys.zoneOrSort] = zoneIDs.ZUL_GURUB,
            [questKeys.specialFlags] = specialFlags.REPEATABLE,
            [questKeys.requiredMinRep] = {factionIDs.ZANDALAR_TRIBE,3000},
            [questKeys.reputationReward] = {{factionIDs.ZANDALAR_TRIBE,250}},
        },
        [95082] = { -- Lunar Prophecy
            [questKeys.name] = "Lunar Prophecy",
            [questKeys.startedBy] = {{15042}},
            [questKeys.finishedBy] = {{15042}},
            [questKeys.requiredLevel] = 80,
            [questKeys.questLevel] = 80,
            [questKeys.requiredRaces] = raceIDs.NONE,
            [questKeys.requiredClasses] = classIDs.DRUID,
            [questKeys.objectives] = {nil,nil,{{274994},{19821}}},
            [questKeys.zoneOrSort] = zoneIDs.ZUL_GURUB,
            [questKeys.specialFlags] = specialFlags.REPEATABLE,
            [questKeys.requiredMinRep] = {factionIDs.ZANDALAR_TRIBE,3000},
            [questKeys.reputationReward] = {{factionIDs.ZANDALAR_TRIBE,250}},
        },
        [95083] = { -- Naturalist's Prophecy
            [questKeys.name] = "Naturalist's Prophecy",
            [questKeys.startedBy] = {{15042}},
            [questKeys.finishedBy] = {{15042}},
            [questKeys.requiredLevel] = 80,
            [questKeys.questLevel] = 80,
            [questKeys.requiredRaces] = raceIDs.NONE,
            [questKeys.requiredClasses] = classIDs.DRUID,
            [questKeys.objectives] = {nil,nil,{{274994},{19821}}},
            [questKeys.zoneOrSort] = zoneIDs.ZUL_GURUB,
            [questKeys.specialFlags] = specialFlags.REPEATABLE,
            [questKeys.requiredMinRep] = {factionIDs.ZANDALAR_TRIBE,3000},
            [questKeys.reputationReward] = {{factionIDs.ZANDALAR_TRIBE,250}},
        },
        [95084] = { -- Dread Prophecy
            [questKeys.name] = "Dread Prophecy",
            [questKeys.startedBy] = {{15042}},
            [questKeys.finishedBy] = {{15042}},
            [questKeys.requiredLevel] = 80,
            [questKeys.questLevel] = 80,
            [questKeys.requiredRaces] = raceIDs.NONE,
            [questKeys.requiredClasses] = classIDs.DEATH_KNIGHT,
            [questKeys.objectives] = {nil,nil,{{274994},{268145}}},
            [questKeys.zoneOrSort] = zoneIDs.ZUL_GURUB,
            [questKeys.specialFlags] = specialFlags.REPEATABLE,
            [questKeys.requiredMinRep] = {factionIDs.ZANDALAR_TRIBE,3000},
            [questKeys.reputationReward] = {{factionIDs.ZANDALAR_TRIBE,250}},
        },
        [95085] = { -- Desecrator's Prophecy
            [questKeys.name] = "Desecrator's Prophecy",
            [questKeys.startedBy] = {{15042}},
            [questKeys.finishedBy] = {{15042}},
            [questKeys.requiredLevel] = 80,
            [questKeys.questLevel] = 80,
            [questKeys.requiredRaces] = raceIDs.NONE,
            [questKeys.requiredClasses] = classIDs.DEATH_KNIGHT,
            [questKeys.objectives] = {nil,nil,{{274994},{268145}}},
            [questKeys.zoneOrSort] = zoneIDs.ZUL_GURUB,
            [questKeys.specialFlags] = specialFlags.REPEATABLE,
            [questKeys.requiredMinRep] = {factionIDs.ZANDALAR_TRIBE,3000},
            [questKeys.reputationReward] = {{factionIDs.ZANDALAR_TRIBE,250}},
        },
        [95088] = { -- Death's Embodiment
            [questKeys.name] = "Death's Embodiment",
            [questKeys.startedBy] = {{15042}},
            [questKeys.finishedBy] = {{15042}},
            [questKeys.requiredLevel] = 80,
            [questKeys.questLevel] = 80,
            [questKeys.requiredRaces] = raceIDs.NONE,
            [questKeys.requiredClasses] = classIDs.ROGUE,
            [questKeys.objectives] = {nil,nil,{{274994},{19814}}},
            [questKeys.zoneOrSort] = zoneIDs.ZUL_GURUB,
            [questKeys.specialFlags] = specialFlags.REPEATABLE,
            [questKeys.requiredMinRep] = {factionIDs.ZANDALAR_TRIBE,3000},
            [questKeys.reputationReward] = {{factionIDs.ZANDALAR_TRIBE,250}},
        },
        [95089] = { -- Arcanist's Embodiment
            [questKeys.name] = "Arcanist's Embodiment",
            [questKeys.startedBy] = {{15042}},
            [questKeys.finishedBy] = {{15042}},
            [questKeys.requiredLevel] = 80,
            [questKeys.questLevel] = 80,
            [questKeys.requiredRaces] = raceIDs.NONE,
            [questKeys.requiredClasses] = classIDs.MAGE,
            [questKeys.objectives] = {nil,nil,{{274994},{19818}}},
            [questKeys.zoneOrSort] = zoneIDs.ZUL_GURUB,
            [questKeys.specialFlags] = specialFlags.REPEATABLE,
            [questKeys.requiredMinRep] = {factionIDs.ZANDALAR_TRIBE,3000},
            [questKeys.reputationReward] = {{factionIDs.ZANDALAR_TRIBE,250}},
        },
        [95090] = { -- Embodiment of Desecration
            [questKeys.name] = "Embodiment of Desecration",
            [questKeys.startedBy] = {{15042}},
            [questKeys.finishedBy] = {{15042}},
            [questKeys.requiredLevel] = 80,
            [questKeys.questLevel] = 80,
            [questKeys.requiredRaces] = raceIDs.NONE,
            [questKeys.requiredClasses] = classIDs.DEATH_KNIGHT,
            [questKeys.objectives] = {nil,nil,{{274994},{268145}}},
            [questKeys.zoneOrSort] = zoneIDs.ZUL_GURUB,
            [questKeys.specialFlags] = specialFlags.REPEATABLE,
            [questKeys.requiredMinRep] = {factionIDs.ZANDALAR_TRIBE,3000},
            [questKeys.reputationReward] = {{factionIDs.ZANDALAR_TRIBE,250}},
        },
        [95092] = { -- Embodiment of Dread
            [questKeys.name] = "Embodiment of Dread",
            [questKeys.startedBy] = {{15042}},
            [questKeys.finishedBy] = {{15042}},
            [questKeys.requiredLevel] = 80,
            [questKeys.questLevel] = 80,
            [questKeys.requiredRaces] = raceIDs.NONE,
            [questKeys.requiredClasses] = classIDs.DEATH_KNIGHT,
            [questKeys.objectives] = {nil,nil,{{274994},{268145}}},
            [questKeys.zoneOrSort] = zoneIDs.ZUL_GURUB,
            [questKeys.specialFlags] = specialFlags.REPEATABLE,
            [questKeys.requiredMinRep] = {factionIDs.ZANDALAR_TRIBE,3000},
            [questKeys.reputationReward] = {{factionIDs.ZANDALAR_TRIBE,250}},
        },
        [95093] = { -- Embodiment of Protection
            [questKeys.name] = "Embodiment of Protection",
            [questKeys.startedBy] = {{15042}},
            [questKeys.finishedBy] = {{15042}},
            [questKeys.requiredLevel] = 80,
            [questKeys.questLevel] = 80,
            [questKeys.requiredRaces] = raceIDs.NONE,
            [questKeys.requiredClasses] = classIDs.WARRIOR,
            [questKeys.objectives] = {nil,nil,{{274994},{19813}}},
            [questKeys.zoneOrSort] = zoneIDs.ZUL_GURUB,
            [questKeys.specialFlags] = specialFlags.REPEATABLE,
            [questKeys.requiredMinRep] = {factionIDs.ZANDALAR_TRIBE,3000},
            [questKeys.reputationReward] = {{factionIDs.ZANDALAR_TRIBE,250}},
        },
        [95094] = { -- Embodiment of Wrath
            [questKeys.name] = "Embodiment of Wrath",
            [questKeys.startedBy] = {{15042}},
            [questKeys.finishedBy] = {{15042}},
            [questKeys.requiredLevel] = 80,
            [questKeys.questLevel] = 80,
            [questKeys.requiredRaces] = raceIDs.NONE,
            [questKeys.requiredClasses] = classIDs.WARRIOR,
            [questKeys.objectives] = {nil,nil,{{274994},{19813}}},
            [questKeys.zoneOrSort] = zoneIDs.ZUL_GURUB,
            [questKeys.specialFlags] = specialFlags.REPEATABLE,
            [questKeys.requiredMinRep] = {factionIDs.ZANDALAR_TRIBE,3000},
            [questKeys.reputationReward] = {{factionIDs.ZANDALAR_TRIBE,250}},
        },
        [95095] = { -- Auratic Embodiment
            [questKeys.name] = "Auratic Embodiment",
            [questKeys.startedBy] = {{15042}},
            [questKeys.finishedBy] = {{15042}},
            [questKeys.requiredLevel] = 80,
            [questKeys.questLevel] = 80,
            [questKeys.requiredRaces] = raceIDs.NONE,
            [questKeys.requiredClasses] = classIDs.PRIEST,
            [questKeys.objectives] = {nil,nil,{{274994},{19820}}},
            [questKeys.zoneOrSort] = zoneIDs.ZUL_GURUB,
            [questKeys.specialFlags] = specialFlags.REPEATABLE,
            [questKeys.requiredMinRep] = {factionIDs.ZANDALAR_TRIBE,3000},
            [questKeys.reputationReward] = {{factionIDs.ZANDALAR_TRIBE,250}},
        },
        [95096] = { -- Destructive Embodiment
            [questKeys.name] = "Destructive Embodiment",
            [questKeys.startedBy] = {{15042}},
            [questKeys.finishedBy] = {{15042}},
            [questKeys.requiredLevel] = 80,
            [questKeys.questLevel] = 80,
            [questKeys.requiredRaces] = raceIDs.NONE,
            [questKeys.requiredClasses] = classIDs.PRIEST,
            [questKeys.objectives] = {nil,nil,{{274994},{19820}}},
            [questKeys.zoneOrSort] = zoneIDs.ZUL_GURUB,
            [questKeys.specialFlags] = specialFlags.REPEATABLE,
            [questKeys.requiredMinRep] = {factionIDs.ZANDALAR_TRIBE,3000},
            [questKeys.reputationReward] = {{factionIDs.ZANDALAR_TRIBE,250}},
        },
        [95097] = { -- Syncretist's Embodiment
            [questKeys.name] = "Syncretist's Embodiment",
            [questKeys.startedBy] = {{15042}},
            [questKeys.finishedBy] = {{15042}},
            [questKeys.requiredLevel] = 80,
            [questKeys.questLevel] = 80,
            [questKeys.requiredRaces] = raceIDs.NONE,
            [questKeys.requiredClasses] = classIDs.PALADIN,
            [questKeys.objectives] = {nil,nil,{{274994},{19815}}},
            [questKeys.zoneOrSort] = zoneIDs.ZUL_GURUB,
            [questKeys.specialFlags] = specialFlags.REPEATABLE,
            [questKeys.requiredMinRep] = {factionIDs.ZANDALAR_TRIBE,3000},
            [questKeys.reputationReward] = {{factionIDs.ZANDALAR_TRIBE,250}},
        },
        [95098] = { -- Divine Embodiment
            [questKeys.name] = "Divine Embodiment",
            [questKeys.startedBy] = {{15042}},
            [questKeys.finishedBy] = {{15042}},
            [questKeys.requiredLevel] = 80,
            [questKeys.questLevel] = 80,
            [questKeys.requiredRaces] = raceIDs.NONE,
            [questKeys.requiredClasses] = classIDs.PALADIN,
            [questKeys.objectives] = {nil,nil,{{274994},{19815}}},
            [questKeys.zoneOrSort] = zoneIDs.ZUL_GURUB,
            [questKeys.specialFlags] = specialFlags.REPEATABLE,
            [questKeys.requiredMinRep] = {factionIDs.ZANDALAR_TRIBE,3000},
            [questKeys.reputationReward] = {{factionIDs.ZANDALAR_TRIBE,250}},
        },
        [95099] = { -- Redeemer's Embodiment
            [questKeys.name] = "Redeemer's Embodiment",
            [questKeys.startedBy] = {{15042}},
            [questKeys.finishedBy] = {{15042}},
            [questKeys.requiredLevel] = 80,
            [questKeys.questLevel] = 80,
            [questKeys.requiredRaces] = raceIDs.NONE,
            [questKeys.requiredClasses] = classIDs.PALADIN,
            [questKeys.objectives] = {nil,nil,{{274994},{19815}}},
            [questKeys.zoneOrSort] = zoneIDs.ZUL_GURUB,
            [questKeys.specialFlags] = specialFlags.REPEATABLE,
            [questKeys.requiredMinRep] = {factionIDs.ZANDALAR_TRIBE,3000},
            [questKeys.reputationReward] = {{factionIDs.ZANDALAR_TRIBE,250}},
        },
        [95100] = { -- Witchdoctor's Embodiment
            [questKeys.name] = "Witchdoctor's Embodiment",
            [questKeys.startedBy] = {{15042}},
            [questKeys.finishedBy] = {{15042}},
            [questKeys.requiredLevel] = 80,
            [questKeys.questLevel] = 80,
            [questKeys.requiredRaces] = raceIDs.NONE,
            [questKeys.requiredClasses] = classIDs.SHAMAN,
            [questKeys.objectives] = {nil,nil,{{274994},{19817}}},
            [questKeys.zoneOrSort] = zoneIDs.ZUL_GURUB,
            [questKeys.specialFlags] = specialFlags.REPEATABLE,
            [questKeys.requiredMinRep] = {factionIDs.ZANDALAR_TRIBE,3000},
            [questKeys.reputationReward] = {{factionIDs.ZANDALAR_TRIBE,250}},
        },
        [95101] = { -- Vodouisant's Embodiment
            [questKeys.name] = "Vodouisant's Embodiment",
            [questKeys.startedBy] = {{15042}},
            [questKeys.finishedBy] = {{15042}},
            [questKeys.requiredLevel] = 80,
            [questKeys.questLevel] = 80,
            [questKeys.requiredRaces] = raceIDs.NONE,
            [questKeys.requiredClasses] = classIDs.SHAMAN,
            [questKeys.objectives] = {nil,nil,{{274994},{19817}}},
            [questKeys.zoneOrSort] = zoneIDs.ZUL_GURUB,
            [questKeys.specialFlags] = specialFlags.REPEATABLE,
            [questKeys.requiredMinRep] = {factionIDs.ZANDALAR_TRIBE,3000},
            [questKeys.reputationReward] = {{factionIDs.ZANDALAR_TRIBE,250}},
        },
        [95102] = { -- Stormcaller's Embodiment
            [questKeys.name] = "Stormcaller's Embodiment",
            [questKeys.startedBy] = {{15042}},
            [questKeys.finishedBy] = {{15042}},
            [questKeys.requiredLevel] = 80,
            [questKeys.questLevel] = 80,
            [questKeys.requiredRaces] = raceIDs.NONE,
            [questKeys.requiredClasses] = classIDs.SHAMAN,
            [questKeys.objectives] = {nil,nil,{{274994},{19817}}},
            [questKeys.zoneOrSort] = zoneIDs.ZUL_GURUB,
            [questKeys.specialFlags] = specialFlags.REPEATABLE,
            [questKeys.requiredMinRep] = {factionIDs.ZANDALAR_TRIBE,3000},
            [questKeys.reputationReward] = {{factionIDs.ZANDALAR_TRIBE,250}},
        },
        [95103] = { -- Guardian's Embodiment
            [questKeys.name] = "Guardian's Embodiment",
            [questKeys.startedBy] = {{15042}},
            [questKeys.finishedBy] = {{15042}},
            [questKeys.requiredLevel] = 80,
            [questKeys.questLevel] = 80,
            [questKeys.requiredRaces] = raceIDs.NONE,
            [questKeys.requiredClasses] = classIDs.DRUID,
            [questKeys.objectives] = {nil,nil,{{274994},{19821}}},
            [questKeys.zoneOrSort] = zoneIDs.ZUL_GURUB,
            [questKeys.specialFlags] = specialFlags.REPEATABLE,
            [questKeys.requiredMinRep] = {factionIDs.ZANDALAR_TRIBE,3000},
            [questKeys.reputationReward] = {{factionIDs.ZANDALAR_TRIBE,250}},
        },
        [95104] = { -- Animist's Embodiment
            [questKeys.name] = "Animist's Embodiment",
            [questKeys.startedBy] = {{15042}},
            [questKeys.finishedBy] = {{15042}},
            [questKeys.requiredLevel] = 80,
            [questKeys.questLevel] = 80,
            [questKeys.requiredRaces] = raceIDs.NONE,
            [questKeys.requiredClasses] = classIDs.DRUID,
            [questKeys.objectives] = {nil,nil,{{274994},{19821}}},
            [questKeys.zoneOrSort] = zoneIDs.ZUL_GURUB,
            [questKeys.specialFlags] = specialFlags.REPEATABLE,
            [questKeys.requiredMinRep] = {factionIDs.ZANDALAR_TRIBE,3000},
            [questKeys.reputationReward] = {{factionIDs.ZANDALAR_TRIBE,250}},
        },
        [95105] = { -- Lunar Embodiment
            [questKeys.name] = "Lunar Embodiment",
            [questKeys.startedBy] = {{15042}},
            [questKeys.finishedBy] = {{15042}},
            [questKeys.requiredLevel] = 80,
            [questKeys.questLevel] = 80,
            [questKeys.requiredRaces] = raceIDs.NONE,
            [questKeys.requiredClasses] = classIDs.DRUID,
            [questKeys.objectives] = {nil,nil,{{274994},{19821}}},
            [questKeys.zoneOrSort] = zoneIDs.ZUL_GURUB,
            [questKeys.specialFlags] = specialFlags.REPEATABLE,
            [questKeys.requiredMinRep] = {factionIDs.ZANDALAR_TRIBE,3000},
            [questKeys.reputationReward] = {{factionIDs.ZANDALAR_TRIBE,250}},
        },
        [95106] = { -- Naturalist's Embodiment
            [questKeys.name] = "Naturalist's Embodiment",
            [questKeys.startedBy] = {{15042}},
            [questKeys.finishedBy] = {{15042}},
            [questKeys.requiredLevel] = 80,
            [questKeys.questLevel] = 80,
            [questKeys.requiredRaces] = raceIDs.NONE,
            [questKeys.requiredClasses] = classIDs.DRUID,
            [questKeys.objectives] = {nil,nil,{{274994},{19821}}},
            [questKeys.zoneOrSort] = zoneIDs.ZUL_GURUB,
            [questKeys.specialFlags] = specialFlags.REPEATABLE,
            [questKeys.requiredMinRep] = {factionIDs.ZANDALAR_TRIBE,3000},
            [questKeys.reputationReward] = {{factionIDs.ZANDALAR_TRIBE,250}},
        },
        [95205] = { -- Greater Inscrptions of the Zandalar
            [questKeys.name] = "Greater Inscrptions of the Zandalar",
            [questKeys.startedBy] = {{14921}},
            [questKeys.finishedBy] = {{14921}},
            [questKeys.requiredLevel] = 80,
            [questKeys.questLevel] = 80,
            [questKeys.requiredRaces] = raceIDs.NONE,
            [questKeys.objectivesText] = {},
            [questKeys.objectives] = {nil,nil,{{19858},{43127}},{270,42000}}, -- TO FIX: need to do {item - rep - item} objective format
            [questKeys.zoneOrSort] = zoneIDs.ZUL_GURUB,
            [questKeys.specialFlags] = specialFlags.REPEATABLE,
            [questKeys.questFlags] = questFlags.NONE,
            [questKeys.requiredMinRep] = {factionIDs.ZANDALAR_TRIBE,42000},
            [questKeys.requiredSkill] = {profKeys.INSCRIPTION,450},
        },
        [95705] = { -- Gobb's Grand Opening!
            [questKeys.name] = "Gobb's Grand Opening!",
            [questKeys.startedBy] = {{262258}},
            [questKeys.finishedBy] = {{262258}},
            [questKeys.requiredLevel] = 80,
            [questKeys.questLevel] = 80,
            [questKeys.requiredRaces] = raceIDs.NONE,
            [questKeys.objectivesText] = {"Boss Gobb Goldnick wants you to purchase one Greedy Chest from his black-market stash to prove you're a paying customer worth fleec-- err, serving."},
            [questKeys.zoneOrSort] = sortKeys.SPECIAL,
            [questKeys.specialFlags] = specialFlags.NONE,
            [questKeys.questFlags] = questFlags.NONE,
            [questKeys.nextQuestInChain] = 95706,
        },
        [95706] = { -- Gobb's Weekly Greed Deal
            [questKeys.name] = "Gobb's Weekly Greed Deal",
            [questKeys.startedBy] = {{262258}},
            [questKeys.finishedBy] = {{262258}},
            [questKeys.requiredLevel] = 80,
            [questKeys.questLevel] = 80,
            [questKeys.requiredRaces] = raceIDs.NONE,
            [questKeys.objectivesText] = {"Purchase a weekly Greedy Chest from Boss Gobb Goldnick's limited stock. Supplies reset every week. If you miss out, tough luck!"},
            [questKeys.zoneOrSort] = sortKeys.SPECIAL,
            [questKeys.specialFlags] = specialFlags.REPEATABLE,
            [questKeys.questFlags] = questFlags.NONE,
            [questKeys.preQuestSingle] = {95705},
        },
        [95844] = { -- Gobb's Grand Tank Temptation
            [questKeys.name] = "Gobb's Grand Tank Temptation",
            [questKeys.startedBy] = {{262258}},
            [questKeys.finishedBy] = {{262258}},
            [questKeys.requiredLevel] = 80,
            [questKeys.questLevel] = 80,
            [questKeys.requiredRaces] = raceIDs.NONE,
            [questKeys.objectivesText] = {"Purchase a weekly Black Qiraji Chest from Boss Gobb Goldnick's limited stock. Supplies reset every week. If you miss out, tough luck!"},
            [questKeys.zoneOrSort] = sortKeys.SPECIAL,
            [questKeys.specialFlags] = specialFlags.NONE,
            [questKeys.questFlags] = questFlags.NONE,
            [questKeys.nextQuestInChain] = 95845,
        },
        [95845] = { -- Another Shot at the Scarab
            [questKeys.name] = "Another Shot at the Scarab",
            [questKeys.startedBy] = {{262258}},
            [questKeys.finishedBy] = {{262258}},
            [questKeys.requiredLevel] = 80,
            [questKeys.questLevel] = 80,
            [questKeys.requiredRaces] = raceIDs.NONE,
            [questKeys.objectivesText] = {"Purchase a weekly Black Qiraji Chest from Boss Gobb Goldnick's limited stock. Supplies reset every week. If you miss out, tough luck!"},
            [questKeys.zoneOrSort] = sortKeys.SPECIAL,
            [questKeys.specialFlags] = specialFlags.REPEATABLE,
            [questKeys.questFlags] = questFlags.NONE,
            [questKeys.preQuestSingle] = {95844},
        },
        [96211] = { -- Heart of the Eredar
            [questKeys.name] = "Heart of the Eredar",
            [questKeys.startedBy] = {nil,nil,{272955}},
            [questKeys.finishedBy] = {{80007}},
            [questKeys.sourceItemId] = 272955,
            [questKeys.requiredLevel] = 80,
            [questKeys.questLevel] = 80,
            [questKeys.requiredRaces] = raceIDs.NONE,
            [questKeys.requiredClasses] = classIDs.WARRIOR + classIDs.HUNTER + classIDs.ROGUE + classIDs.SHAMAN,
            [questKeys.objectivesText] = {"Find a suitable purpose for the Eredar Heart."},
            [questKeys.objectives] = {nil,{{420002}}},
            [questKeys.zoneOrSort] = sortKeys.LEGENDARY,
            [questKeys.specialFlags] = specialFlags.NONE,
            [questKeys.questFlags] = questFlags.NONE,
        },
        [96312] = { -- Brutallus Must Die!
            [questKeys.name] = "Brutallus Must Die!",
            [questKeys.startedBy] = {{20735}},
            [questKeys.finishedBy] = {{20735}},
            [questKeys.requiredLevel] = 80,
            [questKeys.questLevel] = 80,
            [questKeys.requiredRaces] = raceIDs.NONE,
            [questKeys.objectivesText] = {"Kill Brutallus."},
            [questKeys.objectives] = {{{24882}}},
            [questKeys.zoneOrSort] = zoneIDs.SUNWELL_PLATEAU,
            [questKeys.specialFlags] = specialFlags.REPEATABLE,
            [questKeys.questFlags] = questFlags.WEEKLY,
            [questKeys.exclusiveTo] = {93975,94577,94579,95037,96315,96318},
            [questKeys.reputationReward] = {{factionIDs.KIRIN_TOR,75}},
        },
        [96315] = { -- XT-002 Deconstructor Must Die!
            [questKeys.name] = "XT-002 Deconstructor Must Die!",
            [questKeys.startedBy] = {{20735}},
            [questKeys.finishedBy] = {{20735}},
            [questKeys.requiredLevel] = 80,
            [questKeys.questLevel] = 80,
            [questKeys.requiredRaces] = raceIDs.NONE,
            [questKeys.objectivesText] = {"Kill XT-002 Deconstructor."},
            [questKeys.objectives] = {{{33293}}},
            [questKeys.zoneOrSort] = zoneIDs.ULDUAR,
            [questKeys.specialFlags] = specialFlags.REPEATABLE,
            [questKeys.questFlags] = questFlags.WEEKLY,
            [questKeys.exclusiveTo] = {93975,94577,94579,95037,96312,96318},
            [questKeys.reputationReward] = {{factionIDs.KIRIN_TOR,75}},
        },
        [96318] = { -- Shade of Aran Must Die!
            [questKeys.name] = "Shade of Aran Must Die!",
            [questKeys.startedBy] = {{20735}},
            [questKeys.finishedBy] = {{20735}},
            [questKeys.requiredLevel] = 80,
            [questKeys.questLevel] = 80,
            [questKeys.requiredRaces] = raceIDs.NONE,
            [questKeys.objectivesText] = {"Kill Shade of Aran."},
            [questKeys.objectives] = {{{16524}}},
            [questKeys.zoneOrSort] = zoneIDs.KARAZHAN,
            [questKeys.specialFlags] = specialFlags.REPEATABLE,
            [questKeys.questFlags] = questFlags.WEEKLY,
            [questKeys.exclusiveTo] = {93975,94577,94579,95037,96312,96315},
            [questKeys.reputationReward] = {{factionIDs.KIRIN_TOR,75}},
        },
        [98183] = { -- A Ritual Renewed
            [questKeys.name] = "A Ritual Renewed",
            [questKeys.startedBy] = {{14910}},
            [questKeys.finishedBy] = {{14910}},
            [questKeys.requiredLevel] = 80,
            [questKeys.questLevel] = 80,
            [questKeys.requiredRaces] = raceIDs.NONE,
            [questKeys.objectivesText] = {"Accept The Empowered Zandalari Bijou."},
            [questKeys.zoneOrSort] = zoneIDs.ZUL_GURUB,
            [questKeys.specialFlags] = specialFlags.REPEATABLE,
            [questKeys.questFlags] = questFlags.WEEKLY,
        },
    }
end

---Returns runtime overrides for quests inherited from the WotLK database.
---@return table<QuestId, table>
function TitanReforgedQuestFixes.LoadQuestOverrides()
    local questKeys = QuestieDB.questKeys
    local classIDs = QuestieDB.classKeys

    return {
        [6805] = { -- Greater Stormers and Rumblers
            [questKeys.name] = "Greater Stormers and Rumblers",
            [questKeys.questLevel] = 80,
            [questKeys.requiredLevel] = 80,
            [questKeys.objectivesText] = {"Kill 15 Greater Dust Stormers and 15 Greater Desert Rumblers and then return to Duke Hydraxis in Azshara."},
            [questKeys.objectives] = {{{256887},{256889}}},
            [questKeys.nextQuestInChain] = 6822,
        },
        [6822] = { -- The Molten Core
            [questKeys.questLevel] = 80,
            [questKeys.requiredLevel] = 80,
            [questKeys.preQuestSingle] = {6805},
        },
        [6823] = { -- Agent of Hydraxis
            [questKeys.questLevel] = 80,
            [questKeys.requiredLevel] = 80,
        },
        [6824] = { -- Hands of the Enemy
            [questKeys.questLevel] = 80,
            [questKeys.requiredLevel] = 80,
        },
        [7486] = { -- A Hero's Reward
            [questKeys.questLevel] = 80,
            [questKeys.requiredLevel] = 80,
        },
        [7787] = { -- Rise, Thunderfury!
            [questKeys.name] = "Legend of the Past",
            [questKeys.questLevel] = 80,
            [questKeys.requiredLevel] = 80,
            [questKeys.finishedBy] = {{31136}},
            [questKeys.objectivesText] = {"Look for someone who has knowledge about the Dormant Blade."},
            [questKeys.preQuestSingle] = {},
            [questKeys.nextQuestInChain] = 94576,
        },
        [8183] = { -- The Heart of Hakkar
            [questKeys.questLevel] = 80,
            [questKeys.requiredLevel] = 80,
        },
        [8184] = { -- Prophecy of Wrath
            [questKeys.name] = "Prophecy of Wrath",
            [questKeys.questLevel] = 80,
            [questKeys.requiredLevel] = 80,
            [questKeys.objectives] = {nil,nil,{{274994},{19813}}},
        },
        [8185] = { -- Syncretist's Prophecy
            [questKeys.name] = "Syncretist's Prophecy",
            [questKeys.questLevel] = 80,
            [questKeys.requiredLevel] = 80,
            [questKeys.objectives] = {nil,nil,{{274994},{19815}}},
        },
        [8186] = { -- Death's Prophecy
            [questKeys.name] = "Death's Prophecy",
            [questKeys.questLevel] = 80,
            [questKeys.requiredLevel] = 80,
            [questKeys.objectives] = {nil,nil,{{274994},{19814}}},
        },
        [8187] = { -- Falcon's Embodiment
            [questKeys.name] = "Falcon's Embodiment",
            [questKeys.questLevel] = 80,
            [questKeys.requiredLevel] = 80,
            [questKeys.objectives] = {nil,nil,{{274994},{19816}}},
        },
        [8188] = { -- Vodouisant's Prophecy
            [questKeys.name] = "Vodouisant's Prophecy",
            [questKeys.questLevel] = 80,
            [questKeys.requiredLevel] = 80,
            [questKeys.objectives] = {nil,nil,{{274994},{19817}}},
        },
        [8189] = { -- Arcanist's Prophecy
            [questKeys.name] = "Arcanist's Prophecy",
            [questKeys.questLevel] = 80,
            [questKeys.requiredLevel] = 80,
            [questKeys.objectives] = {nil,nil,{{274994},{19818}}},
        },
        [8190] = { -- Hoodoo Prophecy
            [questKeys.name] = "Hoodoo Prophecy",
            [questKeys.questLevel] = 80,
            [questKeys.requiredLevel] = 80,
            [questKeys.objectives] = {nil,nil,{{274994},{19819}}},
        },
        [8191] = { -- Auratic Prophecy
            [questKeys.name] = "Auratic Prophecy",
            [questKeys.questLevel] = 80,
            [questKeys.requiredLevel] = 80,
            [questKeys.objectives] = {nil,nil,{{274994},{19820}}},
        },
        [8192] = { -- Animist's Prophecy
            [questKeys.name] = "Animist's Prophecy",
            [questKeys.questLevel] = 80,
            [questKeys.requiredLevel] = 80,
            [questKeys.objectives] = {nil,nil,{{274994},{19821}}},
        },
        [8195] = { -- Zulian, Razzashi, and Hakkari Coins
            [questKeys.questLevel] = 80,
            [questKeys.requiredLevel] = 80,
        },
        [8196] = { -- Essence Mangoes
            [questKeys.questLevel] = 80,
            [questKeys.requiredLevel] = 80,
        },
        [8201] = { -- A Collection of Heads
            [questKeys.questLevel] = 80,
            [questKeys.requiredLevel] = 80,
        },
        [8227] = { -- Nat's Measuring Tape
            [questKeys.questLevel] = 80,
            [questKeys.requiredLevel] = 80,
        },
        [8238] = { -- Gurubashi, Vilebranch, and Witherbark Coins
            [questKeys.questLevel] = 80,
            [questKeys.requiredLevel] = 80,
        },
        [8239] = { -- Sandfury, Skullsplitter, and Bloodscalp Coins
            [questKeys.questLevel] = 80,
            [questKeys.requiredLevel] = 80,
        },
        [8240] = { -- A Bijou for Zanza
            [questKeys.questLevel] = 80,
            [questKeys.requiredLevel] = 80,
        },
        [8243] = { -- Zanza's Potent Potables
            [questKeys.questLevel] = 80,
            [questKeys.requiredLevel] = 80,
        },
        [8246] = { -- Signets of the Zandalar
            [questKeys.questLevel] = 80,
            [questKeys.requiredLevel] = 80,
        },
        [9250] = { -- Frame of Atiesh
            [questKeys.questLevel] = 80,
            [questKeys.requiredLevel] = 80,
            [questKeys.requiredClasses] = classIDs.SHAMAN + classIDs.MAGE + classIDs.WARLOCK + classIDs.PRIEST + classIDs.DRUID,
        },
        [9251] = { -- Atiesh, the Befouled Greatstaff
            [questKeys.questLevel] = 80,
            [questKeys.requiredLevel] = 80,
            [questKeys.requiredClasses] = classIDs.SHAMAN + classIDs.MAGE + classIDs.WARLOCK + classIDs.PRIEST + classIDs.DRUID,
        },
        [9269] = { -- Atiesh, Greatstaff of the Guardian
            [questKeys.questLevel] = 80,
            [questKeys.requiredLevel] = 80,
            [questKeys.requiredClasses] = classIDs.SHAMAN + classIDs.MAGE + classIDs.WARLOCK + classIDs.PRIEST + classIDs.DRUID,
        },
        [11007] = { -- Kael'thas and the Verdant Sphere
            [questKeys.questLevel] = 80,
            [questKeys.requiredLevel] = 80,
        },
        [11132] = { -- Promises, Promises...
            [questKeys.questLevel] = 80,
            [questKeys.requiredLevel] = 80,
        },
        [11163] = { -- Undercover Sister
            [questKeys.questLevel] = 80,
            [questKeys.requiredLevel] = 80,
        },
        [11164] = { -- Tuskin' Raiders
            [questKeys.questLevel] = 80,
            [questKeys.requiredLevel] = 80,
        },
        [11165] = { -- A Troll Among Trolls
            [questKeys.questLevel] = 80,
            [questKeys.requiredLevel] = 80,
        },
        [11166] = { -- X Marks... Your Doom!
            [questKeys.questLevel] = 80,
            [questKeys.requiredLevel] = 80,
        },
        [11171] = { -- Hex Lord? Hah!
            [questKeys.questLevel] = 80,
            [questKeys.requiredLevel] = 80,
        },
        [11178] = { -- Blood of the Warlord
            [questKeys.questLevel] = 80,
            [questKeys.requiredLevel] = 80,
        },
        [13432] = { -- The Vials of Eternity
            [questKeys.questLevel] = 80,
            [questKeys.requiredLevel] = 80,
        },
    }
end
