dofile("setupTests.lua")

describe("utf8", function()
    ---@type utf8
    local utf8

    before_each(function()
        dofile("Modules/Libs/utf8.lua")
        utf8 = QuestieLoader:ImportModule("utf8")
    end)

    it("converts character and byte positions across two- and four-byte characters", function()
        local text = "aä😀z"
        assert.same({1, 2, 4, 8}, utf8.computeOffsets(text))
        assert.equals(4, utf8.strlen(text))
        assert.equals("ä😀", utf8.sub(text, 2, 3))
        assert.equals("ä😀", utf8.subWithOffsets(text, {1, 2, 4, 8}, 2, 3))
        assert.equals(4, utf8.charIndexToByteIndex(text, 3))
        assert.equals(8, utf8.charIndexToByteIndexWithOffsets({1, 2, 4, 8}, 4, 8))
        assert.equals(9, utf8.charIndexToByteIndex(text, 5))
        assert.equals(1, utf8.charIndexToByteIndex(text, 0))
        assert.equals(2, utf8.byteIndexToCharIndex(text, 3))
        assert.equals(3, utf8.byteIndexToCharIndex(text, 4))
        assert.equals(3, utf8.byteIndexToCharIndex(text, 7))
        assert.equals(4, utf8.byteIndexToCharIndex(text, 8))
        assert.equals(5, utf8.byteIndexToCharIndex(text, 9))
        assert.equals(1, utf8.byteIndexToCharIndex(text, 0))
    end)

    describe("strlen", function()
        it("should count ASCII, CJK, mixed, and empty strings", function()
            assert.are_same(3, utf8.strlen("abc"))
            assert.are_same(2, utf8.strlen("你好"))
            assert.are_same(5, utf8.strlen("a你b好c"))
            assert.are_same(0, utf8.strlen(""))
        end)
    end)

    describe("sub", function()
        it("should slice mixed UTF-8 text by character index", function()
            assert.are_same("你b好", utf8.sub("a你b好c", 2, 4))
        end)

        it("should default nil end index to the last character", function()
            assert.are_same("你b", utf8.sub("a你b", 2))
        end)

        it("should support negative indexes", function()
            assert.are_same("b好", utf8.sub("a你b好", -2, -1))
        end)

        it("should clamp out-of-range indexes", function()
            assert.are_same("a你", utf8.sub("a你", -10, 10))
            assert.are_same("", utf8.sub("a你", 3, 4))
            assert.are_same("", utf8.sub("", 1, 1))
        end)
    end)

    describe("computeOffsets", function()
        it("should compute correct offsets for mixed text", function()
            local offsets = utf8.computeOffsets("a你b")
            assert.are_same({1, 2, 5}, offsets)
        end)

        it("should compute correct offsets for Chinese text", function()
            local offsets = utf8.computeOffsets("收集5个包裹")
            assert.are_same({1, 4, 7, 8, 11, 14}, offsets)
        end)
    end)

    describe("subWithOffsets", function()
        it("should slice using precomputed offsets", function()
            local offsets = utf8.computeOffsets("a你b好c")
            assert.are_same("你b好", utf8.subWithOffsets("a你b好c", offsets, 2, 4))
        end)

        it("should default nil end index to the last character", function()
            local offsets = utf8.computeOffsets("a你b")
            assert.are_same("你b", utf8.subWithOffsets("a你b", offsets, 2))
        end)

        it("should support negative indexes", function()
            local offsets = utf8.computeOffsets("a你b好")
            assert.are_same("b好", utf8.subWithOffsets("a你b好", offsets, -2, -1))
        end)

        it("should clamp out-of-range indexes", function()
            local offsets = utf8.computeOffsets("a你")
            assert.are_same("a你", utf8.subWithOffsets("a你", offsets, -10, 10))
            assert.are_same("", utf8.subWithOffsets("a你", offsets, 3, 4))
            assert.are_same("", utf8.subWithOffsets("", {}, 1, 1))
        end)
    end)

    describe("charIndexToByteIndexWithOffsets", function()
        it("should return byte index using precomputed offsets", function()
            local offsets = utf8.computeOffsets("a你b")
            assert.are_same(1, utf8.charIndexToByteIndexWithOffsets(offsets, 1, 5))
            assert.are_same(2, utf8.charIndexToByteIndexWithOffsets(offsets, 2, 5))
            assert.are_same(5, utf8.charIndexToByteIndexWithOffsets(offsets, 3, 5))
        end)

        it("should return string length + 1 for index > length", function()
            local offsets = utf8.computeOffsets("abc")
            assert.are_same(4, utf8.charIndexToByteIndexWithOffsets(offsets, 5, 3))
        end)

        it("should return 1 for index <= 1", function()
            local offsets = utf8.computeOffsets("abc")
            assert.are_same(1, utf8.charIndexToByteIndexWithOffsets(offsets, 0, 3))
            assert.are_same(1, utf8.charIndexToByteIndexWithOffsets(offsets, 1, 3))
        end)
    end)
end)
