---@type ContentPhases
local ContentPhases = QuestieLoader:ImportModule("ContentPhases")

-- This function blacklists any quests in phases LATER than the currentPhase value
-- so in Phase 1, quests in phases 2+ are blacklisted, in phase 2, phases 3+ are blacklisted, etc
-- Phase 1 is omitted, because everything not in this list is supposed to be available in Phase 1
local questsToBlacklistByPhase = {
    [1] = {}, -- Phase 1 (this is required for counting, but should stay empty)
    [2] = { -- Phase 2 (Patch 5.1 Landfall (Brawlers Guild, New Scenarios)
    },
    [3] = { -- Phase 3 (Patch 5.2 The Thunder King (Isle of Thunder, Throne of Thunder))
        [32200] = true, -- Dangers of Za'Tual
        [32201] = true, -- Grave Circumstances
        [32204] = true, -- The Skumblade Threat
        [32205] = true, -- Gather Scout Reports
        [32206] = true, -- This Just Won't Do
        [32207] = true, -- Saur Loser
        [32208] = true, -- Maximum Capacitor
        [32209] = true, -- Save Our Scouts!
        [32212] = true, -- The Assault on Zeb'tula
        [32213] = true, -- Old Enemies
        [32215] = true, -- Heinous Sacrifice
        [32216] = true, -- Pterrible Ptorment
        [32217] = true, -- Dark Offerings
        [32218] = true, -- Ashes of the Enemy
        [32219] = true, -- Stone Cold
        [32220] = true, -- Soul Surrender
        [32224] = true, -- Rise No More!
        [32225] = true, -- The Call of Thunder
        [32226] = true, -- Into the Crypts
        [32227] = true, -- Preventing a Future Threat
        [32228] = true, -- The Shuddering Moor
        [32230] = true, -- The Zandalari Colossus
        [32232] = true, -- What's Inside Counts
        [32233] = true, -- Very Disarming
        [32234] = true, -- Knowledge Is Power
        [32252] = true, -- Harbingers of the Loa
        [32254] = true, -- Manipulating the Saurok
        [32255] = true, -- De-Constructed
        [32258] = true, -- Horde Quest Choice: PvP
        [32259] = true, -- Horde Quest Choice: PvE
        [32260] = true, -- Alliance Quest Choice: PvE
        [32261] = true, -- Alliance Quest Choice: PvP
        [32262] = true, -- Captive Audience
        [32264] = true, -- Spellbound
        [32265] = true, -- Charged Moganite
        [32266] = true, -- Mana Manifestations
        [32268] = true, -- Tactical Mana Bombs
        [32269] = true, -- Breaking Down the Defenses
        [32274] = true, -- The Residents of Ihgaluk
        [32275] = true, -- Surgical Death
        [32276] = true, -- Tear Down This Wall!
        [32277] = true, -- To the Skies!
        [32278] = true, -- Decisive Action
        [32279] = true, -- The Fall of Shan Bu
        [32282] = true, -- Compy Stomp
        [32283] = true, -- Loa-saur
        [32285] = true, -- The Sleepless Legion
        [32287] = true, -- Enemies Beneath the Tower
        [32288] = true, -- Bolstering the Defenses
        [32292] = true, -- Forge Ahead!
        [32293] = true, -- Among the Bones
        [32294] = true, -- Raining Bones
        [32296] = true, -- Treasures of the Thunder King
        [32297] = true, -- Direhorn or Devilsaur
        [32298] = true, -- Dino Might
        [32299] = true, -- Just Some Light Clean-Up Work
        [32300] = true, -- Disarming Irony
        [32301] = true, -- Old Enemies
        [32302] = true, -- Desconstruction
        [32303] = true, -- Made for War
        [32304] = true, -- High Recognition
        [32305] = true, -- Overpowered
        [32467] = true, -- Sacrificial Prevention [PH]
        [32468] = true, -- Crystal Clarity
        [32469] = true, -- Crystal Clarity
        [32470] = true, -- Light Camera Action
        [32471] = true, -- Light Camera Action
        [32472] = true, -- Frighten Pterodactyls [PH]
        [32485] = true, -- Bolstering the Defenses
        [32489] = true, -- The Creeping Carpet of Ihgaluk
        [32491] = true, -- Left To Rot
        [32492] = true, -- Destroy Cauldrons
        [32493] = true, -- They All Fall Down
        [32494] = true, -- Power Play
        [32495] = true, -- The Bloodletter
        [32496] = true, -- Desecrate this Fire!
        [32497] = true, -- Honor the Flame
        [32498] = true, -- Honor the Flame
        [32499] = true, -- Honor the Flame
        [32500] = true, -- Honor the Flame
        [32501] = true, -- Honor the Flame
        [32502] = true, -- Honor the Flame
        [32503] = true, -- Desecrate this Fire!
        [32506] = true, -- A Wing to Fly On
        [32507] = true, -- Skin of the Saurok
        [32509] = true, -- Honor the Flame
        [32510] = true, -- Honor the Flame
        [32517] = true, -- The Conquest of Stone
        [32518] = true, -- Short-Supply Reward
        [32519] = true, -- Short-Supply Reward
        [32520] = true, -- Competing Magic
        [32521] = true, -- Encroaching Force
        [32522] = true, -- Imposing Threat
        [32523] = true, -- The Beast Pens
        [32524] = true, -- The Beating of Troll Drums
        [32525] = true, -- Ashes of the Enemy
        [32526] = true, -- Soul Surrender
        [32527] = true, -- Grave Circumstances
        [32528] = true, -- Into the Crypts
        [32529] = true, -- The Call of Thunder
        [32530] = true, -- The Bloodletter
        [32531] = true, -- The Conquest of Stone
        [32532] = true, -- Rise No More!
        [32533] = true, -- Stone Cold
        [32535] = true, -- The Skumblade Threat
        [32536] = true, -- Manipulating the Saurok
        [32537] = true, -- De-Constructed
        [32538] = true, -- Heinous Sacrifice
        [32539] = true, -- Dark Offerings
        [32540] = true, -- Harbingers of the Loa
        [32541] = true, -- Preventing a Future Threat
        [32542] = true, -- Surgical Strike
        [32543] = true, -- Dangers of Za'Tual
        [32544] = true, -- Pterrible Ptorment
        [32545] = true, -- The Residents of Ihgaluk
        [32546] = true, -- Just Some Light Clean-Up Work
        [32547] = true, -- The Creeping Carpet of Ihgaluk
        [32548] = true, -- Left To Rot
        [32549] = true, -- Skin of the Saurok
        [32550] = true, -- Saur Loser
        [32551] = true, -- Compy Stomp
        [32552] = true, -- Loa-saur
        [32553] = true, -- Direhorn vs Devilsaur
        [32554] = true, -- Dino Might
        [32555] = true, -- Centuries in Sentries
        [32556] = true, -- The More You Know
        [32557] = true, -- Out of Enemy Hands
        [32558] = true, -- All In the Family
        [32559] = true, -- Even Giants Fall
        [32560] = true, -- Keep It Secret
        [32561] = true, -- Competing Magic
        [32562] = true, -- Imposing Threat
        [32563] = true, -- Encroaching Force
        [32564] = true, -- Zandalari on the Rise
        [32565] = true, -- Encroaching Force
        [32567] = true, -- The Beast Pens
        [32568] = true, -- No Time To Rest
        [32570] = true, -- Gather Scout Reports
        [32571] = true, -- A Wing to Fly On
        [32572] = true, -- The Sleepless Legion
        [32573] = true, -- Enemies Beneath the Tower
        [32574] = true, -- The Shuddering Moor
        [32575] = true, -- The Zandalari Colossus
        [32576] = true, -- Competing Magic
        [32577] = true, -- Imposing Threat
        [32578] = true, -- Among the Bones
        [32579] = true, -- Competing Magic
        [32580] = true, -- Encroaching Force
        [32581] = true, -- Imposing Threat
        [32582] = true, -- Raining Bones
        [32583] = true, -- Zandalari on the Rise
        [32584] = true, -- Encroaching Force
        [32585] = true, -- Encroaching Force
        [32586] = true, -- Maximum Capacitor
        [32587] = true, -- Forge Ahead!
        [32588] = true, -- On Her Magic-ey Secret Service
        [32589] = true, -- Life Blood
        [32599] = true, -- Securing A Future
        [32600] = true, -- The Zandalari Prophecy
        [32601] = true, -- Rumbles of Thunder
        [32602] = true, -- Gods and Monsters
        [32603] = true, -- Beasts of Fable
        [32604] = true, -- Beasts of Fable Book I
        [32605] = true, -- Subtle Encouragement
        [32606] = true, -- Subtle Encouragement
        [32607] = true, -- Extended Shore Leave
        [32608] = true, -- Raiding the Vault
        [32609] = true, -- Rare Chest Tracking Quest
        [32610] = true, -- Rare Boss Tracking Quest
        [32611] = true, -- Rare Drop Tracking Quest
        [32613] = true, -- Giant Dinosaur Bone
        [32614] = true, -- More Giant Dinosaur Bones
        [32615] = true, -- Many More Giant Dinosaur Bones
        [32616] = true, -- A Large Pile of Giant Dinosaur Bones
        [32617] = true, -- A Mountain of Giant Dinosaur Bones
        [32618] = true, -- Learn To Ride
        [32621] = true, -- Lightning Steel
        [32622] = true, -- Intro Flight
        [32626] = true, -- Loot Room Key Tracking Quest
        [32627] = true, -- Charged Moganite
        [32628] = true, -- Tactical Mana Bombs
        [32629] = true, -- Thunderwing Captured Tracking Quest
        [32631] = true, -- High Recognition
        [32632] = true, -- Made for War
        [32633] = true, -- Spellbound
        [32634] = true, -- Breaking Down the Defenses
        [32635] = true, -- Enough with the Bombs!
        [32636] = true, -- Captive Audience
        [32637] = true, -- Overpowered
        [32638] = true, -- Mana Scavengers
        [32639] = true, -- Deconstruction
        [32640] = true, -- Champions of the Thunder King
        [32641] = true, -- Champions of the Thunder King
        [32642] = true, -- Work Order: Dominance Offensive I
        [32643] = true, -- Work Order: Dominance Offensive II
        [32644] = true, -- The Assault on Shaol'mara
        [32645] = true, -- Work Order: Operation: Shieldwall I
        [32646] = true, -- Work Order: Operation: Shieldwall II
        [32647] = true, -- Work Order: Golden Lotus I
        [32648] = true, -- Work Order: Golden Lotus II
        [32649] = true, -- Work Order: Shado-Pan I
        [32650] = true, -- Work Order: Shado-Pan II
        [32652] = true, -- To the Skies!
        [32653] = true, -- Work Order: The August Celestials I
        [32654] = true, -- Tear Down This Wall!
        [32655] = true, -- A Bold Idea
        [32656] = true, -- The Fall of Shan Bu
        [32657] = true, -- Work Order: The August Celestials II
        [32658] = true, -- Work Order: The Klaxxi I
        [32659] = true, -- Work Order: The Klaxxi II
        [32661] = true, -- Learn To Ride
        [32662] = true, -- Learn To Ride
        [32663] = true, -- Learn To Ride
        [32664] = true, -- Learn To Ride
        [32665] = true, -- Learn To Ride
        [32666] = true, -- FLAG - Warlock - Green Fire
        [32667] = true, -- Learn To Ride
        [32668] = true, -- Learn To Ride
        [32669] = true, -- Learn To Ride
        [32670] = true, -- Learn To Ride
        [32671] = true, -- Learn To Ride
        [32672] = true, -- Learn To Ride
        [32673] = true, -- Learn To Ride
        [32676] = true, -- Extended Shore Leave
        [32677] = true, -- Raiding the Vault
        [32678] = true, -- Thunder Calls
        [32679] = true, -- Thunder Calls
        [32680] = true, -- The Storm Gathers
        [32681] = true, -- The Storm Gathers
        [32682] = true, -- Inherit the Earth
        [32683] = true, -- So You Want to Be a Blacksmith...
        [32684] = true, -- You Want Fish?
        [32685] = true, -- No Fishing Pole Necessary!
        [32686] = true, -- Pristine Banner of the Mantid Empire
        [32687] = true, -- Pristine Ancient Sap Feeder
        [32688] = true, -- Pristine Praying Mantid
        [32689] = true, -- Pristine Sound Beacon
        [32690] = true, -- Pristine Remains of a Paragon
        [32691] = true, -- Pristine Mantid Lamp
        [32692] = true, -- Pristine Pollen Collector
        [32693] = true, -- Pristine Kypari Sap Container
        [32694] = true, -- Quest Reward Summary: PvP Stage 1-5
        [32695] = true, -- Quest Reward Summary: PvE Stage 0-2
        [32697] = true, -- Quest Reward Summary: PvE Stage 3
        [32698] = true, -- Quest Reward Summary: PvE Stage 4-5
        [32700] = true, -- Quest Reward Summary: PvP Stage 1-5
        [32701] = true, -- Quest Reward Summary: PvE Stage 0-2
        [32703] = true, -- Quest Reward Summary: PvE Stage 3
        [32704] = true, -- Quest Reward Summary: PvE Stage 4-5
        [32706] = true, -- Allies in the Shadows
        [32707] = true, -- Secrets in the Isle of Thunder
        [32708] = true, -- Setting the Trap
        [32709] = true, -- Allies in the Shadows
        [32710] = true, -- Something Foul is Afoot
        [32711] = true, -- Agony and Anima
        [32712] = true, -- Zao'cho the Wicked
        [32713] = true, -- Rocks Fall, People Die
        [32714] = true, -- Taming the Tempest
        [32715] = true, -- Requiem for a Queen
        [32716] = true, -- Eyes of the Thunder King
        [32720] = true, -- Choose Your Assignment
        [32721] = true, -- Choose Your Assignment
        [32722] = true, -- Forge Ahead!
        [32724] = true, -- Forge Ahead!
        [32725] = true, -- FLAG - Warlock - Reached Kanrethad
        [32726] = true, -- So You Want to Be a Blacksmith...
        [32727] = true, -- Contributed to Server Percentage Daily Tracking Quest
        [32728] = true, -- The Court of Bones
        [32729] = true, -- Za'Tual
        [32730] = true, -- Ihgaluk Crag
        [32731] = true, -- The Court of Bones
        [32732] = true, -- Ihgaluk Crag
        [32733] = true, -- Za'Tual
        [32744] = true, -- Jin'rokh Dead
        [32745] = true, -- Horridon Dead
        [32746] = true, -- Zandalari Council Dead
        [32747] = true, -- Tortos Dead
        [32748] = true, -- Maegaera Dead
        [32749] = true, -- Ji'kun Dead
        [32750] = true, -- Durumu Dead
        [32751] = true, -- Primordious Dead
        [32752] = true, -- Dark Animus Dead
        [32753] = true, -- Ra-Den Dead
        [32754] = true, -- Iron Qon Dead
        [32755] = true, -- Empyreal Queens Dead
        [32756] = true, -- Lei Shen Dead
        [32758] = true, -- Reader for the Dead Tongue
    },
    [4] = { -- Phase 4 (Patch 5.3 Escalation (Deepwind Gorge, New Scenarios, Heroic Scenarios))
        [32806] = true, -- The King and the Council
        [32807] = true, -- The Warchief and the Darkness
        [32816] = true, -- Path of the Last Emperor
        [32863] = true, -- What We've Been Training For
        [32868] = true, -- Beasts of Fable Book II
        [32869] = true, -- Beasts of Fable Book III
        [32900] = true, -- Heroic Deeds
        [32901] = true, -- Heroic Deeds
    },
    [5] = { -- Phase 5 (Patch 5.4 Siege of Orgrimmar (Raid, Timeless Isle, Proving Grounds)
    },
}

---@param questsToBlacklist table<QuestId, boolean>
---@param contentPhase number
---@return table<QuestId, boolean>
function ContentPhases.BlacklistMoPQuestsByPhase(questsToBlacklist, contentPhase)
    for phase = contentPhase + 1, #questsToBlacklistByPhase do
        for questId in pairs(questsToBlacklistByPhase[phase]) do
            questsToBlacklist[questId] = true
        end
    end

    return questsToBlacklist
end
