---@meta _

---@alias AnimationDataEnum number
---@alias ArtifactTiers number
---@alias BigInteger number
---@alias BigUInteger number
---@alias CalendarEventID number
---@alias ClubId string
---@alias ClubInvitationId string
---@alias ClubStreamId string
---@alias ConnectionIptype number 1=IPv4, 2=IPv6
---@alias FileAsset string
---@alias fileID integer
---@alias GarrisonFollower string
---@alias HTMLTextType string
---@alias IDOrLink number|string
---@alias InventorySlots number
---@alias ItemInfo number|string
---@alias kstringClubMessage string
---@alias kstringLfgListApplicant string
---@alias kstringLfgListSearch string
---@alias luaFunction function
---@alias LuaValueVariant table
---@alias ModelAsset number FileID
---@alias normalizedValue number [0.0 - 1.0]
---@alias NotificationDbId string
---@alias QuestObjectiveType number
---@alias RecruitAcceptanceID string
---@alias SingleColorValue number
---@alias size number
---@alias SpellIdentifier number|string
---@alias stringView string
---@alias TextureAsset fileID|string|Texture
---@alias TextureAssetDisk fileID|string
---@alias textureAtlas string
---@alias textureKit string
---@alias time_t number
---@alias uiAddon string|number
---@alias uiFontHeight number
---@alias uiUnit number
---@alias WeeklyRewardItemDBID string
---@alias WOWGUID string
---@alias WOWMONEY number
