---@meta _
-- does not include pet and target suffices and spectated<T><N>
-- but any string is accepted anyway

---@alias UnitToken string
---|"player"
---|"target"
---|"focus"
---|"mouseover"
---|"pet"
---|"vehicle"
---|"npc"
---|"questnpc"
---|"none"
---|"party1"
---|"raid1"
---|"arena1"
---|"boss1"
---|"nameplate1"
---|"anyenemy"
---|"anyfriend"
---|"anyinteract"
---|"softenemy"
---|"softfriend"
---|"softinteract"

---@alias UnitTokenNamePlate UnitToken
---@alias UnitTokenRestrictedForAddOns UnitToken
---@alias UnitTokenPvPRestrictedForAddOns UnitToken
