#!/bin/sh
#!/usr/bin/env python
echo "-->Running pre-commit script!";
#Run build script".
python build.py
echo "\n-->Adding the changed QuestieDev-master.toc!";
git add QuestieDev-master.toc
git status
echo "--Pre-commit script done!";