# Label for Classic Era/HC quests
era/hc:
  - '### Game flavor\s*Era/HC'

anniversary:
  - '### Game flavor\s*Anniversary'

# Label for Classic Seasonal quests
Season of Discovery:
  - '### Game flavor\s*Season of Discovery'

# Label for WotLK quests
wotlk:
  - '### Game flavor\s*WotLK'

# Label for Cata quests
cata:
  - '### Game flavor\s*Cata'
