import csv

faction_template_file = '../DBC - WoW.tools/FactionTemplate.5.5.0.61051.csv'
output_file = 'factionTemplate.lua'

with open(faction_template_file, 'r') as csvfile, open(output_file, 'w') as luafile:
    reader = csv.DictReader(csvfile)
    rows = []
    for row in reader:
        entryId = row['ID'].strip()
        enemy_group = row['EnemyGroup'].strip()
        if entryId and enemy_group:
            rows.append((int(entryId), enemy_group))
    rows.sort()
    luafile.write('-- File was auto-generated by generateFactionTemplate.py\n\n')
    luafile.write('---@type QuestieDB\n')
    luafile.write('local QuestieDB = QuestieLoader:ImportModule("QuestieDB")\n\n')
    luafile.write('---@type table<FactionId, EnemyGroup>\n')
    luafile.write('QuestieDB.factionTemplate = {\n')
    for entryId, enemy_group in rows:
        luafile.write(f'    [{entryId}] = {enemy_group},\n')
    luafile.write('}\n')
