print("reading questxp_cata.csv")
local questXpDBC = io.open("../DBC - WoW.tools/questxp_cata.csv", "r")
local questXpLines = {}
for line in questXpDBC:lines() do
    if line == "" then
        break
    end
    local parts = {}
    for part in line:gmatch("[^,]+") do
        table.insert(parts, part)
    end

    questXpLines[tonumber(parts[1])] = {parts[2], parts[3], parts[4], parts[5], parts[6], parts[7], parts[8], parts[9], parts[10]}
end
questXpDBC:close()

-- data.csv can be extracted from mangos/trinity with: SELECT entry, QuestLevel, RewXPId FROM quest_template;
print("reading data.lua")
local inputFile = io.open("data.csv", "r")
local lines = {}
for line in inputFile:lines() do
    if line == "" then
        break
    end
    local parts = {}
    for part in line:gmatch("[^,]+") do
        table.insert(parts, part)
    end

    local questId, questLevel, xpId = parts[1], tonumber(parts[2]), tonumber(parts[3])
    if questLevel == -1 then
        questLevel = 1 -- For "scaling quests", the reward XP is the one for the lowest level
    end
    if questLevel == 0 or questLevel == 255 then
        questLevel = 1
        xpId = 0
    end

    local xpReward = questXpLines[questLevel][xpId + 1]

    table.insert(lines, "  [" .. questId .. "] = {" .. questLevel .. ", " .. xpReward .. "},")
end
inputFile:close()

print("writing to xpDB.lua")
local outputFile = io.open("xpDB.lua", "w")

-- Add the header
outputFile:write("--! This file is automatically generated. Do not modify\n\n")
outputFile:write("---@type QuestXP\n")
outputFile:write("local QuestXP = QuestieLoader:ImportModule(\"QuestXP\")\n\n")

outputFile:write("QuestXP.db = {\n")
for _, line in ipairs(lines) do
    outputFile:write(line .. "\n")
end
outputFile:write("}\n")
outputFile:close()

print("done")
