---@meta _
---@class AppearanceSourceInfo
---@field visualID number
---@field sourceID number
---@field isCollected boolean
---@field itemID number
---@field itemModID number
---@field invType number? Default = 0
---@field categoryID Enum.TransmogCollectionType? Default = None
---@field playerCanCollect boolean
---@field isValidSourceForPlayer boolean
---@field canDisplayOnPlayer boolean
---@field inventorySlot number?
---@field sourceType number?
---@field name string?
---@field quality number?
---@field useError string?
---@field useErrorType Enum.TransmogUseErrorType?
---@field meetsTransmogPlayerCondition boolean?
---@field isHideVisual boolean?
