---@meta _
---@class CharacterAlternateFormData
---@field raceID number
---@field name string
---@field fileName string
---@field createScreenIconAtlas textureAtlas

---@class PlayerInfoCharacterData
---@field name string
---@field fileName string
---@field alternateFormRaceData CharacterAlternateFormData?
---@field createScreenIconAtlas textureAtlas
---@field sex Enum.UnitSex
