---@meta _
---@class QuestPOIMapInfo
---@field childDepth number?
---@field questTagType Enum.QuestTagType?
---@field questID number
---@field numObjectives number
---@field mapID number
---@field x number
---@field y number
---@field isQuestStart boolean
---@field isDaily boolean
---@field isCombatAllyQuest boolean
---@field isMeta boolean
---@field inProgress boolean
---@field isMapIndicatorQuest boolean
