---@meta _
---@class QueueSpecificInfo
---@field queueType string
---@field lfgIDs number[]?
---@field lfgListID number?
---@field activityID number?
---@field battlefieldType string?
---@field listID number?
---@field mapName string?
---@field rated boolean?
---@field isBrawl boolean?
---@field teamSize number?
