---@meta _
---@class AnchorBinding
---@field point FramePoint
---@field relativeTo ScriptRegion
---@field relativePoint FramePoint
---@field offsetX uiUnit
---@field offsetY uiUnit

---@class uiBoundsRect
---@field left uiUnit
---@field bottom uiUnit
---@field width uiUnit
---@field height uiUnit
