---@meta _
---@class ChatChannelInfo
---@field name string
---@field shortcut string
---@field localID number
---@field instanceID number
---@field zoneChannelID number
---@field channelType Enum.PermanentChatChannelType
