---@meta _
---@class ContentTrackingMapInfo
---@field x number
---@field y number
---@field trackableType Enum.ContentTrackingType
---@field trackableID number
---@field targetType Enum.ContentTrackingTargetType
---@field targetID number
---@field waypointText string

---@class EncounterTrackingInfo
---@field encounterName string
---@field journalEncounterID number?
---@field journalInstanceID number?
---@field instanceName string
---@field subText string?
---@field difficultyID number?
---@field lfgDungeonID number?
---@field groupFinderActivityID number?

---@class VendorTrackingInfo
---@field creatureName string
---@field zoneName string?
---@field currencyType number?
---@field cost BigUInteger?
