---@meta _
---@class EncounterEventInfo
---@field encounterEventID number
---@field enabled boolean
---@field spellID number
---@field iconFileID number
---@field severity Enum.EncounterEventSeverity
---@field icons Enum.EncounterEventIconmask
---@field color colorRGB?

---@class EncounterEventSoundInfo
---@field file FileAsset
---@field channel UISoundSubType? Default = g_defaultSI3UISoundSubTypeForLua
---@field volume number? Default = 1
