---@meta _
---@class MythicPlusAffixScoreInfo
---@field name string
---@field score number
---@field level number
---@field durationSec number
---@field overTime boolean

---@class MythicPlusRatingLinkInfo
---@field mapChallengeModeID number
---@field level number
---@field completedInTime number
---@field dungeonScore number
---@field name string
