---@meta _
---@class SpellChargeInfo
---@field currentCharges number
---@field maxCharges number
---@field cooldownStartTime number
---@field cooldownDuration number
---@field chargeModRate number
---@field isActive boolean

---@class SpellCooldownInfo
---@field startTime number
---@field duration number
---@field isEnabled boolean
---@field isActive boolean
---@field modRate number
---@field activeCategory number?
---@field timeUntilEndOfStartRecovery number?
---@field isOnGCD boolean?

---@class SpellLossOfControlInfo
---@field startTime number
---@field duration number
---@field modRate number
---@field isActive boolean
---@field shouldReplaceNormalCooldown boolean

---@class SpellPowerCostInfo
---@field type Enum.PowerType
---@field name string
---@field cost number
---@field minCost number
---@field costPercent number
---@field costPerSec number
---@field requiredAuraID number
---@field hasRequiredAura boolean
