---@type AutoQuesting
local AutoQuesting = QuestieLoader:ImportModule("AutoQuesting")
local _AutoQuesting = AutoQuesting.private

_AutoQuesting.disallowedNPCs = {
    -- AQ
    -- Ally
    [15176] = true, -- Vargus (Silithus combat assignments
    [15458] = true, -- Commander Stronghammer (Alliance Ambassador)
    [15701] = true, -- Field Marshal Snowfall (War Effort Commander)
    -- Horde
    [15539] = true, -- General Zog (Horde Ambassador)
    [15700] = true, -- Warlord Gorchuk (War Effort Commander)
    -- Commendations
    [15764] = true, -- Officer Ironbeard (Ironforge Commendations)
    [15762] = true, -- Officer Lunalight (Darnassus Commendations)
    [15766] = true, -- Officer Maloof (Stormwind Commendations)
    [15763] = true, -- Officer Porterhouse (Gnomeregan Commendations)
    [15768] = true, -- Officer Gothena (Undercity Commendations)
    [15765] = true, -- Officer Redblade (Orgrimmar Commendations)
    [15767] = true, -- Officer Thunderstrider (Thunder Bluff Commendations)
    [15761] = true, -- Officer Vu'Shalay (Darkspear Commendations)
    [15731] = true, -- Darnassus Commendation Officer
    [15737] = true, -- Darkspear Commendation Officer
    [15735] = true, -- Stormwind Commendation Officer
    [15739] = true, -- Thunder Bluff Commendation Officer
    [15736] = true, -- Orgrimmar Commendation Officer
    [15734] = true, -- Ironforge Commendation Officer
    [15738] = true, -- Undercity Commendation Officer
    [15733] = true, -- Gnomeregan Commendation Officer
    -- AQ gear turnin
    [15378] = true, -- Merithra of the Dream
    [15380] = true, -- Arygos
    [15498] = true, -- Windcaller Yessendra
    [15499] = true, -- Warden Haro
    [15500] = true, -- Keyl Swiftclaw
    [15503] = true, -- Kandrostrasz
    -- Stray
    [7802] = true, -- Galvan the Ancient (Blacksmith recipes, Stranglethorn Vale)
    [12944] = true, -- Lokhtos Darkbargainer (Thorium Brotherhood, Blackrock Depths)
    [14567] = true, -- Derotain Mudsipper (Blacksmith recipes, Tanaris)
    [14828] = true, -- Gelvas Grimegate (Darkmoon Faire Ticket Redemption)
    [14921] = true, -- Rin'wosho the Trader (Zul'Gurub Isle, Stranglethorn Vale)
    [15192] = true, -- Anachronos (Caverns of Time)
    [15909] = true, -- Fariel Starsong <Coin of Ancestry Collector> (Lunar Festival)
    [16786] = true, -- Argent Quartermaster (Scourge Invasion turn ins)
    [18166] = true, -- Khadgar (Allegiance to Aldor/Scryer, Shattrath)
    [18253] = true, -- Archmage Leryda (Violet Eye)
    [18471] = true, -- Gurgthock (The Ring of Blood)
    [19935] = true, -- Soridormi (The Scale of Sands)
    [19936] = true, -- Arazmodu (The Scale of Sands)
    [25112] = true, -- Anchorite Ayuri (Shattered Sun Offensive Charity NPC)
    [25163] = true, -- Anchorite Kairthos (Shattered Sun Offensive Title NPC)
}

_AutoQuesting.disallowedQuests = {
    accept = {
        -- Escort Quests
        [155] = true, -- The Defias Traitor (The Defias Brotherhood)
        [219] = true, -- Corporal Keeshan (Missing In Action)
        [309] = true, -- Miran (Protecting the Shipment)
        [349] = true, -- Stranglethorn Fever (Consumes items)
        [434] = true, -- Tyrion (The Attack!)
        [435] = true, -- Deathstalker Erland (Escorting Erland)
        [648] = true, -- Homing Robot OOX-17/TN (Rescue OOX-17/TN!)
        [660] = true, -- Kinelory (Hints of a New Plague?)
        [665] = true, -- Professor Phizzlethorpe (Sunken Treasure)
        [667] = true, -- Shakes O'Breen (Death From Below)
        [731] = true, -- Prospector Remtravel (The Absent Minded Prospector)
        [836] = true, -- Homing Robot OOX-09/HL (Rescue OOX-09/HL!)
        [863] = true, -- Wizzlecrank's Shredder (The Escape)
        [898] = true, -- Gilthares Firebough (Free From the Hold)
        [938] = true, -- Mist (Mist)
        [945] = true, -- Therylune (Therylune's Escape)
        [976] = true, -- Feero Ironhand (Supplies to Auberdine)
        [994] = true, -- Volcor (Escape Through Force)
        [995] = true, -- Volcor (Escape Through Stealth)
        [1144] = true, -- Willix the Importer (Willix the Importer)
        [1120] = true, -- Get the Gnomes Drunk
        [1121] = true, -- Get the Goblins Drunk
        [1222] = true, -- Stinky Ignatz (Stinky's Escape)
        [1270] = true, -- Stinky Ignatz (Stinky's Escape)
        [1273] = true, -- Ogron (Questioning Reethe)
        [1324] = true, -- Private Hendel (The Missing Diplomat)
        [1393] = true, -- Galen Goodward (Galen's Escape)
        [1440] = true, -- Dalinda Malem (Return to Vahlarriel)
        [1560] = true, -- Tooga (Tooga's Quest)
        [2742] = true, -- Rin'ji (Rin'ji is Trapped!)
        [2767] = true, -- Homing Robot OOX-22/FE (Rescue OOX-22/FE!)
        [2845] = true, -- Shay Leafrunner (Wandering Shay)
        [2904] = true, -- Kernobee (A Fine Mess)
        [3367] = true, -- Dorius Stonetender (Suntara Stones)
        [3382] = true, -- Captain Vanessa Beltis (A Crew Under Fire)
        [3525] = true, -- Belnistrasz (Extinguishing the Idol)
        [3526] = true, -- Goblin Engineering (NPC 4586)
        [3629] = true, -- Goblin Engineering (NPC 5174)
        [3630] = true, -- Gnome Engineering (NPC 5518)
        [3632] = true, -- Gnome Engineering (NPC 5174)
        [3633] = true, -- Goblin Engineering (NPC 3494)
        [3634] = true, -- Gnome Engineering (NPC 3494)
        [3635] = true, -- Gnome Engineering (NPC 4586)
        [3644] = true, -- Goblin Membership Card Renewal
        [3645] = true, -- Gnome Membership Card Renewal
        [3646] = true, -- Goblin Membership Card Renewal
        [3647] = true, -- Gnome Membership Card Renewal
        [3982] = true, -- Commander Gor'shak (What Is Going On?)
        [4121] = true, -- Grark Lorkrub (Precarious Predicament)
        [4181] = true, -- Goblin Engineering (NPC 5518)
        [4245] = true, -- A-Me 01 (Chasing A-Me 01)
        [4261] = true, -- Arei (Ancient Spirit)
        [4322] = true, -- Marshal Windsor (Jail Break!)
        [4491] = true, -- Ringo (A Little Help From My Friends)
        [4770] = true, -- Pao'ka Swiftmountain (Homeward Bound)
        [4901] = true, -- Ranshalla (Guardians of the Altar)
        [4904] = true, -- Lakota Windsong (Free at Last)
        [4962] = true, -- Shard of a Felhound Warlock special quest
        [4963] = true, -- Shard of an Infernal Warlock special quest
        [4966] = true, -- Kanati Greycloud (Protect Kanati Greycloud)
        [5162] = true, -- Wrath of the Blue Flight (Flies you from Winterspring to WPL)
        [5203] = true, -- Captured Arko'narin (Rescue From Jaedenar)
        [5321] = true, -- Kerlonian Evershade (The Sleeper Has Awakened)
        [5713] = true, -- Sentinel Aynasha (One Shot. One Kill.)
        [5821] = true, -- Cork Gizelton (Bodyguard for Hire)
        [5943] = true, -- Rigger Gizelton (Gizelton Caravan)
        [5944] = true, -- Highlord Taelan Fordring (In Dreams)
        [6132] = true, -- Melizza Brimbuzzle (Get Me Out of Here!)
        [6403] = true, -- Reginald Windsor (The Great Masquerade)
        [6482] = true, -- Ruul Snowhoof (Freedom to Ruul)
        [6523] = true, -- Kaya Flathoof (Protect Kaya)
        [6544] = true, -- Torek (Torek's Assault)
        [6641] = true, -- Muglash (Vorsha the Lasher)
        [7046] = true, -- Celebras the Redeemed (The Scepter of Celebras)
        [9212] = true, -- Escape from the Catacombs
        [9446] = true, -- Tomb of the Lightbringer
        [9528] = true, -- A Cry For Help
        [9729] = true, -- Fhwoor Smash!
        [9752] = true, -- Escape from Umbrafen
        [9868] = true, -- The Totem of Kar'dash
        [9879] = true, -- The Totem of Kar'dash
        [10051] = true, -- Escape from Firewing Point!
        [10052] = true, -- Escape from Firewing Point!
        [10191] = true, -- Mark V is Alive!
        [10218] = true, -- Someone Else's Hard Work Pays Off
        [10310] = true, -- Sabotage the Warp-Gate!
        [10337] = true, -- When the Cows Come Home
        [10406] = true, -- Delivering the Message
        [10425] = true, -- Escape from the Staging Grounds
        [10451] = true, -- Escape from Coilskar Cistern
        [10898] = true, -- Skywing
        [10922] = true, -- Digging Through Bones
        [11085] = true, -- Escape from Skettis
        [11189] = true, -- One Last Time
        [11241] = true, -- Trail of Fire
        [11570] = true, -- Escape from the Winterfin Caverns
        [11664] = true, -- Escaping the Mist
        [11673] = true, -- Get Me Outa Here!
        [11705] = true, -- Foolish Endeavors
        [11930] = true, -- Across Transborea
        [12082] = true, -- Dun-da-Dun-tah!
        [12570] = true, -- Fortunate Misunderstandings
        [12688] = true, -- Engineering a Disaster
        [12832] = true, -- Bitter Departure
        [13221] = true, -- I'm Not Dead Yet!
        [13229] = true, -- I'm Not Dead Yet!
        [13284] = true, -- Assault by Ground
        [13301] = true, -- Assault by Ground
        [13481] = true, -- Let's Get Out of Here!
        [13482] = true, -- Let's Get Out of Here
        [25476] = true, -- Rescue OOX-22/FE!
        ---
        [10346] = true, -- Gryphoneer Windbellow (Return to the Abyssal Shelf) (Alliance)
        [10347] = true, -- Wing Commander Brack (Return to the Abyssal Shelf) (Horde)
        [11733] = true, -- Traversing the Rift (Flies you to Coldarra)
        [12174] = true, -- High Commander Halford Wyrmbane (Flies you across Dragonblight)
        [12671] = true, -- Reconnaissance Flight (Flies you across the Sholazar Basin)
        [13926] = true, -- Little Orphan Roo of the Oracles (exclusive to the Wolvar)
        [13927] = true, -- Little Orphan Kekek of the Wolvar (exclusive to the Oracles)
        [27022] = true, -- Extinguishing the Idol
        ---
        [29205] = true, -- The Forlorn Spire
        [29206] = true, -- Into the Fire
    },
    turnIn = {
        [2199] = true, -- Lore for a Price (crafting material objectives)
        [2948] = true, -- Gnome Improvement (crafting material and gold objectives)
        [2950] = true, -- Gnome Improvement (crafting material and gold objectives)
        [3375] = true, -- Replacement Phial (crafting material objectives)
        [3644] = true, -- Goblin Membership Card Renewal
        [3645] = true, -- Gnome Membership Card Renewal
        [3646] = true, -- Goblin Membership Card Renewal
        [3647] = true, -- Gnome Membership Card Renewal
        [4083] = true, -- The Spectral Chalice (crafting material objectives)
        [4781] = true, -- Components for the Enchanted Gold Bloodrobe (crafting material objectives)
        [5063] = true, -- Cap of the Scarlet Savant (crafting material objectives)
        [5067] = true, -- Leggings of Arcana (crafting material objectives)
        [5068] = true, -- Breastplate of Bloodthirst (crafting material objectives)
        [5166] = true, -- Breastplate of the Chromatic Flight (crafting material objectives)
        [5167] = true, -- Legplates of the Chromatic Defier (crafting material objectives)
        [7637] = true, -- Emphasis on Sacrifice (Gold objective)
        [8196] = true, -- Essence Mangoes (ZG Turn-In)
        [8783] = true, -- Extraordinary Materials (crafting material objectives)
        [8809] = true, -- Extraordinary Materials (crafting material objectives)
        [9338] = true, -- Allegiance to Cenarion Circle
        [10975] = true, -- Purging the Chambers of Bash'ir (Ethereum Prison Key exchange)
        -- Netherwing Drake quests
        [11109] = true,
        [11110] = true,
        [11111] = true,
        [11112] = true,
        [11113] = true,
        [11114] = true,
        -- The Barrens Bloodshard quests
        [889] = true,
        [5042] = true,
        [5043] = true,
        [5044] = true,
        [5045] = true,
        [5046] = true,
        -- PvP token quests
        [8367] = true,
        [8388] = true,
        [8371] = true,
        [8385] = true,
        [64845] = true,
        -- AQ
        [8548] = true,
        [8572] = true,
        [8573] = true,
        [8574] = true,
        [8288] = true,
        -- Aldor/scryer quests
        [10551] = true,
        [10552] = true,
        --
        [12567] = true, -- Blessing of Zim'Abwa repeatable
        [12618] = true, -- Blessing of Zim'Torga repeatable
        [12656] = true, -- Blessing of Zim'Rhuk repeatable
        [82062] = true, -- Ever After SoD
        [83934] = true, -- Show Me The Money! - Costs one Tarnished Undermine Real
    }
}
