name: Package Addon

on:
  push:
    branches: [ master ]
    tags: [ "*" ]

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Clone project
        uses: actions/checkout@v1

      - name: Package and release Wrath
        uses: BigWigsMods/packager@master
        with:
          args: -g wrath