name: Package Addon

on:
  push:
    tags: [ "*" ]

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      GH_TOKEN: ${{ github.token }}
      #CF_API_KEY: ${{ secrets.CF_API_KEY }}
      #GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Clone project
        uses: actions/checkout@v1

      - name: Generate Changelog
        id: changelog
        run: python changelog.py >> CHANGELOG.md

      - name: Build ZIP
        run: python build.py -r

      - name: Create GitHub release
        run: >
          gh release create ${{github.ref_name}}
          --verify-tag
          --draft
          -F CHANGELOG.md
          releases/${{github.ref_name}}/Questie-${{github.ref_name}}.zip
          releases/${{github.ref_name}}/release.json

      - name: Upload CurseForge
        run: sh upload-cf.sh ${{github.ref_name}}

      - name: Upload WAGO
        run: sh upload-wago.sh ${{github.ref_name}}

#      - name: Upload GitHub artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: Questie-${{github.sha}}
#          path: .release/Questie-*.zip

